import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import type {AddressInfo} from 'node:net';
import type {InstallationLocation,Database,StockRecord} from '../shared/types';
import {locationKinds} from '../shared/types';
import {createApp} from '../server/app';
import {Store,encodeCSV,decodeCSV} from '../server/store';
import {seed} from '../server/seed';
import {schemas} from '../server/schema';
import {checkInstalledPC} from '../shared/inventory';
import {distributionVacancies} from '../shared/location-operations';
const location=(id:string,kind:InstallationLocation['kind'],parentId=''):InstallationLocation=>({id,name:id,kind,parentId,requirementSetId:'',requirementRevision:0,targetConfigurationId:'',notes:'Original notes'});
function fixture(){const db=structuredClone(seed);db.inventory=[];db.installationLocations=[location('site','Site'),location('area-a','Room','site'),location('area-b','Room','site'),location('line-a','Line','area-a'),location('station-a','Station','line-a'),location('station-b','Station','line-a')];db.pcs[0].installationLocationId='station-a';db.pcs[0].lifecycle='Planning';return db;}
async function workspace(run:(context:{db:Database;store:Store;call:(route:string,body:unknown,method?:string,revision?:string)=>Promise<Response>})=>Promise<void>){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bench-bulk-'));const app=createApp(dir),store=app.locals.store as Store,db=fixture();store.restore(db);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;try{await run({db,store,call:(route,body,method='POST',revision=store.revision)=>fetch(origin+route,{method,headers:{'Content-Type':'application/json','If-Match':revision},body:JSON.stringify(body)})});}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));fs.rmSync(dir,{recursive:true,force:true});}}
const patchRequest={collection:'installationLocations',action:'edit',ids:['area-a','area-b'],patch:{kind:'Area',notes:{mode:'append',value:'Production areas'}}};
test('production location types and legacy Room round-trip CSV without requiring room levels',()=>{const records=locationKinds.map(kind=>location(kind.toLowerCase(),kind));for(const row of records)assert(schemas.installationLocations.safeParse(row).success);assert.deepEqual(decodeCSV('installationLocations',encodeCSV('installationLocations',records)),records);const db=fixture();assert(!checkInstalledPC(db.pcs[0],db).findings.some(f=>f.title==='PC location must be a leaf'));assert(distributionVacancies(db).some(l=>l.id==='station-b'));});
test('bulk preview is read-only and room-to-area edits preserve assignments and descendants atomically',async()=>workspace(async({store,call})=>{const before=store.revision,preview=await (await call('/api/bulk/preview',patchRequest)).json();assert.equal(preview.valid,true);assert.equal(preview.rows.length,2);assert.equal(preview.affectedPCs,1);assert.equal(store.revision,before);assert.equal((await call('/api/bulk/apply',{request:patchRequest,token:preview.token},'PUT',preview.revision)).status,200);assert.equal(store.db.installationLocations.find(l=>l.id==='area-a')!.kind,'Area');assert.equal(store.db.installationLocations.find(l=>l.id==='area-b')!.notes,'Original notes\nProduction areas');assert.equal(store.db.installationLocations.find(l=>l.id==='line-a')!.parentId,'area-a');assert.equal(store.db.pcs[0].installationLocationId,'station-a');}));
test('bulk preview and apply protect stale revisions and altered reviewed requests',async()=>workspace(async({store,call})=>{const preview=await (await call('/api/bulk/preview',patchRequest)).json();const altered={...patchRequest,ids:['area-a']};assert.equal((await call('/api/bulk/apply',{request:altered,token:preview.token},'PUT')).status,409);store.replace('installationLocations',store.db.installationLocations.map(l=>l.id==='area-b'?{...l,notes:'Other editor'}:l));assert.equal((await call('/api/bulk/apply',{request:patchRequest,token:preview.token},'PUT',preview.revision)).status,409);assert.equal(store.db.installationLocations.find(l=>l.id==='area-a')!.kind,'Room');}));
test('bulk deletion blocks unselected children and assigned PCs and permits an explicitly selected empty subtree',async()=>workspace(async({store,call})=>{let request={collection:'installationLocations',action:'delete',ids:['area-a']};let preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,false);assert.match(preview.error,/unselected child/);request={...request,ids:['station-a']};preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,false);assert.match(preview.error,/assigned PCs/);store.replace('installationLocations',[...store.db.installationLocations,location('empty-line','Line','area-b'),location('empty-station','Station','empty-line')]);request={...request,ids:['empty-line','empty-station']};preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,true);assert.equal((await call('/api/bulk/apply',{request,token:preview.token},'PUT')).status,200);assert(!store.db.installationLocations.some(l=>l.id==='empty-line'||l.id==='empty-station'));}));
test('bulk hierarchy cycles and changes making assigned PC locations nonassignable leave all records intact',async()=>workspace(async({store,call})=>{const before=store.revision;for(const request of [{collection:'installationLocations',action:'edit',ids:['area-a','area-b'],patch:{parentId:'line-a'}},{collection:'installationLocations',action:'edit',ids:['station-a','station-b'],patch:{kind:'Area'}}]){const preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,false);assert.equal(store.revision,before);}assert.equal(store.db.installationLocations.find(l=>l.id==='station-b')!.kind,'Station');}));
test('bulk requirements use canonical published snapshots rather than inherited or caller supplied data',async()=>workspace(async({store,call})=>{const version={revision:1,at:'2026-10-09T00:00:00Z',name:'Production station',description:'',connections:[]};store.replace('requirementsSets',[{id:'production',name:'Production needs',description:'',versions:[version]}]);const request={collection:'installationLocations',action:'edit',ids:['station-a','station-b'],patch:{requirements:{setId:'production',revision:1}}},preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,true);assert.equal((await call('/api/bulk/apply',{request,token:preview.token},'PUT')).status,200);for(const l of store.db.installationLocations.filter(l=>l.id.startsWith('station')))assert.deepEqual(l.requirementSnapshot,version);}));
test('bulk PC relocation creates per-PC timelines and preserves allocation whereabouts and build plans',async()=>workspace(async({store,call})=>{const pc=store.db.pcs[0],beforeConfiguration=pc.configurationId;const stock:StockRecord={id:'installed-part',componentId:store.db.components[0].id,tracking:'bulk',quantity:1,serial:'',assetTag:'',condition:'Serviceable',location:'Stock home',notes:'',history:[],allocations:[{id:'actual-part',pcId:pc.id,quantity:1,state:'installed',plannedPlacementId:'',slotId:'',role:'general',mount:'auto',notes:'',createdAt:'2026-10-09T00:00:00Z',updatedAt:'2026-10-09T00:00:00Z'}]};store.replace('inventory',[stock]);const request={collection:'pcs',action:'edit',ids:[pc.id],patch:{installationLocationId:'station-b',lifecycle:'Maintenance',notes:{mode:'append',value:'Inspect before restart'}}},preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,true);assert.equal((await call('/api/bulk/apply',{request,token:preview.token},'PUT')).status,200);const next=store.db.pcs[0];assert.equal(next.installationLocationId,'station-b');assert.equal(next.configurationId,beforeConfiguration);assert(next.timeline!.at(-1)!.summary.includes('station-b'));assert.equal(store.db.inventory[0].allocations[0].pcId,pc.id);assert.equal(store.db.inventory[0].location,'Stock home');}));
test('bulk PC deletion and retirement block both installed allocations and reservations with no partial changes',async()=>workspace(async({store,call})=>{const pc=store.db.pcs[0];const stock:StockRecord={id:'reserved-part',componentId:store.db.components[0].id,tracking:'bulk',quantity:1,serial:'',assetTag:'',condition:'Serviceable',location:'Stock home',notes:'',history:[],allocations:[{id:'reserved-allocation',pcId:pc.id,quantity:1,state:'reserved',plannedPlacementId:'',slotId:'',role:'general',mount:'auto',notes:'',createdAt:'2026-10-09T00:00:00Z',updatedAt:'2026-10-09T00:00:00Z'}]};store.replace('inventory',[stock]);const before=store.revision;for(const request of [{collection:'pcs',action:'delete',ids:store.db.pcs.map(p=>p.id)},{collection:'pcs',action:'edit',ids:store.db.pcs.map(p=>p.id),patch:{lifecycle:'Retired'}}]){const preview=await (await call('/api/bulk/preview',request)).json();assert.equal(preview.valid,false);assert.equal(store.revision,before);}const response=await call('/api/bulk/preview',{collection:'pcs',action:'edit',ids:[pc.id],patch:{lifecycle:'In service'}});assert.equal(response.status,400);}));
test('bulk changes reject duplicate unknown IDs and unsupported fields without writes',async()=>workspace(async({store,call})=>{const before=store.revision;for(const request of [{...patchRequest,ids:['area-a','area-a']},{...patchRequest,patch:{name:'Duplicate names'}},{collection:'pcs',action:'edit',ids:[store.db.pcs[0].id],patch:{configurationId:store.db.configurations[0].id}}])assert.equal((await call('/api/bulk/preview',request)).status,400);const preview=await (await call('/api/bulk/preview',{...patchRequest,ids:['area-a','missing']})).json();assert.equal(preview.valid,false);assert.equal(store.revision,before);}));
