import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed} from '../server/seed';
import {checkConfiguration} from '../shared/compatibility';
import type {Placement} from '../shared/types';
const setup=()=>{const db=structuredClone(seed);return {db,config:db.configurations[0]};};
const has=(result:ReturnType<typeof checkConfiguration>,title:string)=>result.findings.some(f=>f.title===title&&f.severity==='error');
test('illustrative imaging build fits declared resources and calculates two mirrors',()=>{const {db,config}=setup();const r=checkConfiguration(config,db);assert.equal(r.findings.filter(f=>f.severity==='error').length,0);assert.equal(r.usableDataGb,8000);assert.equal(r.bootGb,1000);assert.equal(Object.keys(r.slotAssignments).length,3);assert.equal(r.status,'Needs review');});
test('conventional PCI is not interchangeable with PCIe, and instrument ports are counted',()=>{const {db}=setup();const r=checkConfiguration(db.configurations[1],db);assert.ok(has(r,'No compatible expansion slot'));assert.ok(has(r,'USB-A ports capacity exceeded'));assert.ok(has(r,'Ethernet ports capacity exceeded'));});
test('physical x16 does not imply 16 electrical lanes',()=>{const {db,config}=setup();const gpu=db.components.find(c=>c.id==='gpu')!;gpu.specs.requiredLanes=16;config.placements.find(p=>p.componentId==='gpu')!.slotId='PCIE_2';assert.ok(has(checkConfiguration(config,db),'No compatible expansion slot'));});
test('adjacent brackets block slots even when connectors are free',()=>{const {db,config}=setup();db.components.find(c=>c.id==='board-atx')!.specs.slots![1].position=2;config.placements.find(p=>p.componentId==='gpu')!.slotId='PCIE_1';assert.ok(has(checkConfiguration(config,db),'Expansion slots cannot be allocated'));});
test('auto allocator preserves scarce slots rather than assigning greedily',()=>{const {db,config}=setup();config.placements=config.placements.filter(p=>!['nic','daq'].includes(p.componentId));const board=db.components.find(c=>c.id==='board-atx')!;board.specs.ethernet=2;board.specs.slots=[{id:'LARGE',bus:'PCIe',physical:16,lanes:16,generation:4,position:1},{id:'SMALL',bus:'PCIe',physical:4,lanes:4,generation:3,position:4}];config.placements.unshift({id:'small-first',componentId:'daq',quantity:1,slotId:'',role:'general',mount:'auto',group:''});const r=checkConfiguration(config,db);assert.equal(r.slotAssignments['small-first:0'],'SMALL');assert.equal(r.findings.filter(f=>f.severity==='error').length,0);});
test('rear sled consumes slot lanes, capacity and bifurcation support',()=>{const {db}=setup();const config=db.configurations[2];const r=checkConfiguration(config,db);assert.equal(r.findings.filter(f=>f.severity==='error').length,0);assert.equal(r.bootGb,1000);db.components.find(c=>c.id==='board-atx')!.specs.bifurcation=false;assert.ok(has(checkConfiguration(config,db),'PCIe bifurcation required'));config.placements.find(p=>p.componentId==='nvme')!.quantity=3;assert.ok(has(checkConfiguration(config,db),'Rear sled positions capacity exceeded'));});
test('SATA port and power budgets and front bays are checked independently',()=>{const {db,config}=setup();config.placements.find(p=>p.componentId==='hdd')!.quantity=7;const r=checkConfiguration(config,db);assert.ok(has(r,'SATA ports capacity exceeded'));assert.ok(has(r,'Front hot-swap bays capacity exceeded'));db.components.find(c=>c.id==='psu')!.specs.sataPower=1;assert.ok(has(checkConfiguration(config,db),'SATA power plugs capacity exceeded'));});
test('socket, memory generation, card dimensions and power conflicts are detected',()=>{const {db,config}=setup();db.components.find(c=>c.id==='cpu')!.specs.socket='LGA1700';db.components.find(c=>c.id==='ram')!.specs.memoryType='DDR4';db.components.find(c=>c.id==='gpu')!.specs.lengthMm=400;db.components.find(c=>c.id==='psu')!.specs.capacityW=100;const r=checkConfiguration(config,db);for(const title of ['CPU socket mismatch','Memory type mismatch','Card exceeds length clearance','Power with 25% headroom capacity exceeded'])assert.ok(has(r,title));});
test('RAID capacity uses smallest member and invalid groups report zero usable data',()=>{const {db,config}=setup();config.placements.find(p=>p.componentId==='hdd')!.quantity=1;config.placements.push({id:'ssd-data',componentId:'ssd',quantity:1,slotId:'',role:'data',mount:'internal',group:''});assert.equal(checkConfiguration(config,db).usableDataGb,2000);config.storage.raid='raid5';let r=checkConfiguration(config,db);assert.equal(r.usableDataGb,0);assert.ok(has(r,'Invalid data redundancy layout'));config.placements.find(p=>p.componentId==='hdd')!.quantity=3;r=checkConfiguration(config,db);assert.equal(r.usableDataGb,6000);config.storage.raid='raid6';assert.equal(checkConfiguration(config,db).usableDataGb,4000);config.storage.raid='raid10';assert.equal(checkConfiguration(config,db).usableDataGb,4000);});
test('incomplete live quantity inputs never crash the report',()=>{const {db,config}=setup();for(const value of [0,-1,1.5,NaN,'']){config.placements[0].quantity=value as number;assert.ok(has(checkConfiguration(config,db),'Invalid component quantity'));}});
test('unknown resource capacity requires review rather than implying zero',()=>{const {db,config}=setup();delete db.components.find(c=>c.id==='board-atx')!.specs.usbA;const r=checkConfiguration(config,db);assert.ok(r.findings.some(f=>f.title==='USB-A ports capacity unknown'&&f.severity==='warning'));assert.ok(!has(r,'USB-A ports capacity exceeded'));});

test('slot backtracking preserves an explicitly connected SATA endpoint while allowing safe unused-port sharing',()=>{
 const {db,config}=setup();config.systemId='';config.placements=config.placements.filter(p=>!['gpu','nic'].includes(p.componentId));
 const board=db.components.find(c=>c.id==='board-atx')!,bp=config.placements.find(p=>p.componentId===board.id)!,daq=config.placements.find(p=>p.componentId==='daq')!;daq.slotId='';
 board.specs.slots=[{id:'SHARED',bus:'PCIe',physical:4,lanes:4,generation:4,position:1},{id:'SAFE',bus:'PCIe',physical:4,lanes:4,generation:4,position:4}];
 board.specs.sataDataPorts=Array.from({length:6},(_,i)=>({id:`SATA${i+1}`}));board.specs.laneRules=[{id:'sata-share',slots:['SHARED'],disableSataPortIds:['SATA1'],disableSataPorts:1}];
 const disk=config.placements.find(p=>p.componentId==='hdd')!;disk.quantity=1;disk.sataDataConnections=[{controllerPlacementId:bp.id,portId:'SATA1'}];config.placements.push({...structuredClone(disk),id:'second-hdd',sataDataConnections:[{controllerPlacementId:bp.id,portId:'SATA2'}]});
 const safe=checkConfiguration(config,db);assert.equal(safe.slotAssignments[`${daq.id}:0`],'SAFE');assert.ok(!has(safe,'SATA data endpoint disabled'));assert.ok(!has(safe,'Expansion slots cannot be allocated'));
 daq.slotId='SHARED';assert.ok(has(checkConfiguration(config,db),'Expansion slots cannot be allocated'));
 daq.slotId='';disk.sataDataConnections[0].portId='SATA3';const shared=checkConfiguration(config,db);assert.equal(shared.slotAssignments[`${daq.id}:0`],'SHARED');assert.equal(shared.resources.find(r=>r.name==='SATA ports')!.available,5);assert.ok(!has(shared,'SATA data endpoint disabled'));
});

test('optical drives retain SATA and bay requirements but never add legacy capacity to boot or data arrays',()=>{
 const {db,config}=setup();const baseline=checkConfiguration(config,db);db.components.find(c=>c.category==='Chassis')!.specs.bays525=1;
 db.components.push({id:'optical',name:'DVD drive',category:'Drive',manufacturer:'Example',source:'',verified:true,specs:{driveKind:'optical',driveSize:'5.25',driveInterface:'SATA',capacityGb:999999,powerW:20,lengthMm:150}});
 const optical:Placement={id:'optical-placement',componentId:'optical',quantity:1,role:'data',mount:'internal',slotId:'',group:''};config.placements.push(optical);
 for(const role of ['data','boot'] as const){optical.role=role;const report=checkConfiguration(config,db);assert.equal(report.bootGb,baseline.bootGb);assert.equal(report.usableDataGb,baseline.usableDataGb);assert.ok(has(report,'Optical drive storage role invalid'));assert.equal(report.resources.find(r=>r.name==='SATA ports')!.used,3);assert.equal(report.resources.find(r=>r.name==='5.25-inch bays')!.used,1);}
 optical.role='general';assert.ok(!has(checkConfiguration(config,db),'Optical drive storage role invalid'));
});
