import { test } from 'node:test';
import assert from 'node:assert/strict';
import { seed } from '../server/seed';
import { schemas } from '../server/schema';
import { checkConfiguration } from '../shared/compatibility';
import { checkInstalledPC } from '../shared/inventory';
import { encodeCSV, decodeCSV } from '../server/store';
import type { Port, PortRequirement, RequirementVersion, StockRecord } from '../shared/types';
const setup=()=>{const db=structuredClone(seed),config=db.configurations[0],board=db.components.find(c=>c.id==='board-atx')!,line=config.placements.find(p=>p.componentId===board.id)!,system=db.systems.find(s=>s.id===config.systemId)!;for(const c of db.components.filter(c=>['Motherboard','Scientific card','Network card','Storage adapter','GPU'].includes(c.category)))c.specs.ports=[];system.connections=[{id:'instrument',name:'Scientific instrument',usbA:0,usbC:0,ethernet:0,notes:'',requirements:[]}];return {db,config,board,line,connection:system.connections[0]};};
const has=(r:ReturnType<typeof checkConfiguration>,title:string,severity='error')=>r.findings.some(f=>f.title===title&&f.severity===severity);
const port=(id:string,kind:Port['kind'],more:Partial<Port>={}):Port=>({id,kind,...more});
const required=(id:string,kind:PortRequirement['kind'],more:Partial<PortRequirement>={}):PortRequirement=>({id,kind,quantity:1,...more});
test('Serial and Parallel explicit catalogs and requirements validate and round-trip CSV',()=>{
 const {db,board,connection}=setup();board.specs.ports=[port('COM1','Serial',{connector:'DE-9',pinout:'DTE',protocol:'RS-232'}),port('LPT1','Parallel',{connector:'DB-25',pinout:'IEEE1284',protocol:'IEEE 1284'})];connection.requirements=[required('serial','Serial'),required('parallel','Parallel')];assert.ok(schemas.components.safeParse(board).success);assert.ok(schemas.systems.safeParse(db.systems[0]).success);assert.deepEqual(decodeCSV('components',encodeCSV('components',[board])),[schemas.components.parse(board)]);assert.deepEqual(decodeCSV('systems',encodeCSV('systems',[db.systems[0]])),[schemas.systems.parse(db.systems[0])]);
});
test('Custom ports and requirements reject absent or whitespace-only interface types',()=>{
 const {board,db,connection}=setup();for(const customType of [undefined,'','  ']){board.specs.ports=[port('X','Custom',{customType})];assert.ok(!schemas.components.safeParse(board).success);connection.requirements=[required('X','Custom',{customType})];assert.ok(!schemas.systems.safeParse(db.systems[0]).success);}board.specs.ports=[port('X','Custom',{customType:'Trigger bus'})];connection.requirements=[required('X','Custom',{customType:'Trigger bus'})];assert.ok(schemas.components.safeParse(board).success);assert.ok(schemas.systems.safeParse(db.systems[0]).success);
});
test('mapped custom interfaces, connectors and pinouts normalize case and whitespace',()=>{
 const {db,config,board,line,connection}=setup();board.specs.ports=[port('P1','Custom',{customType:' Trigger bus ',connector:' db-25 ',pinout:' Lab-A ',protocol:' TTL '})];connection.requirements=[required('trigger','Custom',{customType:'TRIGGER BUS',connector:'DB-25',pinout:'lab-a',protocol:'ttl'})];config.portMappings=[{connectionId:connection.id,requirementId:'trigger',placementId:line.id,instance:0,portId:'P1'}];const r=checkConfiguration(config,db);assert.ok(!has(r,'Equipment custom type mismatch'));assert.ok(!has(r,'Equipment connector mismatch'));assert.ok(!has(r,'Equipment pinout mismatch'));assert.ok(!has(r,'Equipment protocol mismatch'));assert.ok(!has(r,'Equipment ports cannot be allocated'));
});
test('mapped named custom interfaces cannot satisfy other custom names, connectors or pinouts',()=>{
 const {db,config,board,line,connection}=setup();board.specs.ports=[port('P1','Custom',{customType:'Trigger',connector:'DE-9',pinout:'Vendor-B'})];connection.requirements=[required('trigger','Custom',{customType:'Camera link',connector:'DB-25',pinout:'Vendor-A'})];config.portMappings=[{connectionId:connection.id,requirementId:'trigger',placementId:line.id,instance:0,portId:'P1'}];const r=checkConfiguration(config,db);for(const title of ['Equipment custom type mismatch','Equipment connector mismatch','Equipment pinout mismatch'])assert.ok(has(r,title));assert.ok(has(r,'Custom ports (Camera link) capacity exceeded'));
});
test('unknown provider connector and pinout require review without inventing incompatibility',()=>{
 const {db,config,board,line,connection}=setup();board.specs.ports=[port('COM1','Serial',{protocol:'RS-232'})];connection.requirements=[required('serial','Serial',{connector:'DE-9',pinout:'DTE',protocol:'RS-232'})];config.portMappings=[{connectionId:connection.id,requirementId:'serial',placementId:line.id,instance:0,portId:'COM1'}];const r=checkConfiguration(config,db);assert.ok(has(r,'Equipment connector unknown','warning'));assert.ok(has(r,'Equipment pinout unknown','warning'));assert.ok(!has(r,'Equipment ports cannot be allocated'));assert.ok(!has(r,'Equipment connector mismatch'));
});
test('unmapped Serial and Parallel requirements use explicit capacity with component quantities and no chassis ports',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=[port('COM1','Serial'),port('LPT1','Parallel')];connection.requirements=[required('serial','Serial',{quantity:3}),required('parallel','Parallel',{quantity:2})];db.components.find(c=>c.category==='Chassis')!.specs.ports=[port('COMX','Serial')];const daq=db.components.find(c=>c.id==='daq')!;daq.specs.ports=[port('COM2','Serial')];config.placements.find(p=>p.componentId==='daq')!.quantity=2;const r=checkConfiguration(config,db);assert.equal(r.resources.find(r=>r.name==='Serial ports')?.available,3);assert.ok(!has(r,'Serial ports capacity exceeded'));assert.ok(has(r,'Parallel ports capacity exceeded'));assert.ok(has(r,'Equipment ports not mapped','warning'));
});
test('explicit absence is known zero while undeclared Serial interfaces remain unknown',()=>{
 const {db,config,board,connection}=setup();connection.requirements=[required('serial','Serial')];for(const component of db.components)delete component.specs.ports;let r=checkConfiguration(config,db);assert.ok(has(r,'Serial ports capacity unknown','warning'));assert.ok(!has(r,'Serial ports capacity exceeded'));for(const component of db.components.filter(c=>['Motherboard','Scientific card','Network card','Storage adapter','GPU'].includes(c.category)))component.specs.ports=[];r=checkConfiguration(config,db);assert.ok(has(r,'Serial ports capacity exceeded'));assert.ok(has(r,'Equipment ports cannot be allocated'));
});
test('different custom interface types have independent capacity pools',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=[port('TRIG','Custom',{customType:'Trigger'}),port('CAM','Custom',{customType:'Camera link'})];connection.requirements=[required('trigger','Custom',{customType:'trigger',quantity:2}),required('camera','Custom',{customType:'CAMERA LINK'})];const r=checkConfiguration(config,db);assert.ok(has(r,'Custom ports (trigger) capacity exceeded'));assert.ok(!has(r,'Custom ports (CAMERA LINK) capacity exceeded'));assert.equal(r.resources.find(r=>r.name==='Custom ports (CAMERA LINK)')?.available,1);
});
test('non-Custom interface names do not change Serial matching',()=>{
 const {db,config,board,line,connection}=setup();board.specs.ports=[port('COM1','Serial',{customType:'Unused provider label'})];connection.requirements=[required('serial','Serial',{customType:'Unrelated requirement label'})];config.portMappings=[{connectionId:connection.id,requirementId:'serial',placementId:line.id,instance:0,portId:'COM1'}];const r=checkConfiguration(config,db);assert.ok(!has(r,'Equipment custom type mismatch'));assert.ok(!has(r,'Serial ports capacity exceeded'));assert.ok(!has(r,'Equipment ports cannot be allocated'));
});
test('insufficient compatible Serial protocol and connector capacity is found before port mapping',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=[port('COM1','Serial',{protocol:'RS-232',connector:'DE-9'})];connection.requirements=[required('serial','Serial',{protocol:'RS-485',connector:'RJ45'})];const r=checkConfiguration(config,db);assert.ok(!has(r,'Serial ports capacity exceeded'));assert.ok(r.findings.some(f=>f.severity==='error'&&f.title.startsWith('Compatible Serial ports')));assert.ok(has(r,'Equipment ports cannot be allocated'));
});
test('compatible allocation accounts for contention and keeps scarce ports for constrained requirements',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=[port('COM1','Serial',{protocol:'RS-232'}),port('COM2','Serial',{protocol:'RS-485'})];connection.requirements=[required('flexible','Serial'),required('rs232','Serial',{protocol:'RS-232'})];let r=checkConfiguration(config,db);assert.ok(!has(r,'Equipment ports cannot be allocated'));connection.requirements.push(required('another232','Serial',{protocol:'RS-232'}));board.specs.ports.push(port('COM3','Serial',{protocol:'RS-485'}));r=checkConfiguration(config,db);assert.ok(!has(r,'Serial ports capacity exceeded'));assert.ok(has(r,'Equipment ports cannot be allocated'));
});
test('explicit mappings reserve scarce physical ports before allocating other requirements',()=>{
 const {db,config,board,line,connection}=setup();board.specs.ports=[port('COM1','Serial',{protocol:'RS-232'}),port('COM2','Serial',{protocol:'RS-485'})];connection.requirements=[required('flexible','Serial'),required('rs232','Serial',{protocol:'RS-232'})];config.portMappings=[{connectionId:connection.id,requirementId:'flexible',placementId:line.id,instance:0,portId:'COM1'}];let r=checkConfiguration(config,db);assert.ok(has(r,'Equipment ports cannot be allocated'));config.portMappings[0].portId='COM2';r=checkConfiguration(config,db);assert.ok(!has(r,'Equipment ports cannot be allocated'));
});
test('installation pinned Custom requirements use actual installed ports and include location resource rollups',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=[port('TRIG','Custom',{customType:'Trigger'})];const version:RequirementVersion={revision:1,at:'2026-10-08T10:00:00Z',name:'Trigger instrument',description:'',connections:[{...connection,requirements:[required('trigger','Custom',{customType:'Trigger',quantity:2})]}]};db.requirementsSets=[{id:'trigger',name:'Trigger',description:'',versions:[version]}];db.installationLocations=[{id:'bench',name:'Bench',kind:'Bench',parentId:'',requirementSetId:'trigger',requirementRevision:1,requirementSnapshot:version,targetConfigurationId:'',notes:''}];const pc=db.pcs[0];pc.installationLocationId='bench';db.inventory=config.placements.map((p,i)=>({id:`stock-${i}`,componentId:p.componentId,tracking:'bulk',serial:'',assetTag:'',quantity:p.quantity,location:'Stock',condition:'Serviceable',notes:'',history:[],allocations:[{id:`allocation-${i}`,pcId:pc.id,quantity:p.quantity,state:'installed',plannedPlacementId:p.id,slotId:p.slotId,role:p.role,mount:p.mount,group:p.group,notes:'',createdAt:version.at,updatedAt:version.at}]} satisfies StockRecord));const r=checkInstalledPC(pc,db);assert.ok(has(r,'Custom ports (Trigger) capacity exceeded'));assert.equal(r.resources.find(r=>r.name==='Installation Custom ports (Trigger)')?.used,2);
});

test('partial port catalogs cannot establish a definite Serial shortage or absence',()=>{
 const {db,config,board,connection}=setup();delete board.specs.ports;connection.requirements=[required('serial','Serial')];const report=checkConfiguration(config,db);assert.ok(has(report,'Serial ports capacity unknown','warning'));assert.ok(has(report,'Equipment port catalog incomplete','warning'));assert.ok(!has(report,'Serial ports capacity exceeded'));assert.ok(!has(report,'Equipment ports cannot be allocated'));
});
test('known card ports satisfy Serial demand even when motherboard interfaces remain undocumented',()=>{
 const {db,config,board,connection}=setup();delete board.specs.ports;db.components.find(c=>c.id==='daq')!.specs.ports=[port('COM1','Serial')];connection.requirements=[required('serial','Serial')];const report=checkConfiguration(config,db);assert.equal(report.resources.find(resource=>resource.name==='Serial ports')?.available,1);assert.ok(!has(report,'Serial ports capacity unknown','warning'));assert.ok(!has(report,'Equipment ports cannot be allocated'));assert.ok(has(report,'Equipment ports not mapped','warning'));
});
test('known mapped protocol mismatch remains an error despite other undocumented providers',()=>{
 const {db,config,board,line,connection}=setup();delete db.components.find(c=>c.id==='daq')!.specs.ports;board.specs.ports=[port('COM1','Serial',{protocol:'RS-232'})];connection.requirements=[required('serial','Serial',{protocol:'RS-485'})];config.portMappings=[{connectionId:connection.id,requirementId:'serial',placementId:line.id,instance:0,portId:'COM1'}];const report=checkConfiguration(config,db);assert.ok(has(report,'Equipment protocol mismatch'));assert.ok(has(report,'Equipment port capacity incomplete','warning'));assert.ok(!has(report,'Equipment ports cannot be allocated'));
});
test('large demand candidate products require review without building an unbounded allocation graph',()=>{
 const {db,config,board,connection}=setup();board.specs.ports=Array.from({length:400},(_,i)=>port(`COM${i}`,'Serial'));connection.requirements=Array.from({length:400},(_,i)=>required(`serial${i}`,'Serial'));const report=checkConfiguration(config,db);assert.ok(has(report,'Equipment port allocation review','warning'));assert.ok(!has(report,'Equipment ports cannot be allocated'));
});
