import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../server/store';
import {EnrichmentQueue} from '../server/enrichment';
import {createApp} from '../server/app';
const html=(brand:string)=>`<script type="application/ld+json">${JSON.stringify({'@type':'Product',name:'Test CPU',brand})}</script>`;
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bench-queue-')),store=new Store(dir);store.replace('components',[...store.db.components,{id:'test-cpu',name:'Test CPU',manufacturer:'',source:'',category:'CPU',verified:true,specs:{}}]);return {dir,store,cleanup:()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
const waitIdle=async(queue:EnrichmentQueue)=>{for(let i=0;i<100&&queue.running;i++)await new Promise(r=>setTimeout(r,5));assert.equal(queue.running,false);};
test('replacing a proposal requires reviewing its new token',()=>{const {store,cleanup}=setup();const q=new EnrichmentQueue(store);try{const job=q.enqueue([{componentId:'test-cpu',url:'https://pcpartpicker.com/product/abc/test'}])[0];q.upload(job.id,html('AMD'));const token=job.proposalId!;q.upload(job.id,html('Intel'));assert.throws(()=>q.apply(job.id,['manufacturer'],token),/proposal changed/);assert.equal(store.db.components.find(c=>c.id==='test-cpu')!.manufacturer,'');q.apply(job.id,['manufacturer'],job.proposalId!);assert.equal(store.db.components.find(c=>c.id==='test-cpu')!.manufacturer,'Intel');assert(store.db.components.find(c=>c.id==='test-cpu')!.specs.notes!.includes(job.url));}finally{q.close();cleanup();}});
test('cancel followed by pause cannot resurrect a completed in-flight response',async()=>{const {store,cleanup}=setup();let resolve!:(html:string)=>void;const q=new EnrichmentQueue(store,()=>new Promise<string>(r=>resolve=r));try{const job=q.enqueue([{componentId:'test-cpu',url:'https://pcpartpicker.com/product/abc/test'}])[0];q.start();q.cancel(job.id);q.pause();resolve(html('AMD'));await waitIdle(q);assert.equal(job.state,'cancelled');assert.equal(store.getEnrichmentJobs()[0].state,'cancelled');}finally{q.close();cleanup();}});
test('close during fetch prevents late writes and reopening makes interrupted work retryable',async()=>{const {store,dir,cleanup}=setup();let resolve!:(html:string)=>void;const q=new EnrichmentQueue(store,()=>new Promise<string>(r=>resolve=r));const job=q.enqueue([{componentId:'test-cpu',url:'https://pcpartpicker.com/product/abc/test'}])[0];q.start();q.close();store.close();resolve(html('AMD'));await waitIdle(q);const reopened=new Store(dir),queue=new EnrichmentQueue(reopened);try{assert.equal(queue.jobs[0].id,job.id);assert.equal(queue.jobs[0].state,'queued');assert.equal(queue.running,false);}finally{queue.close();reopened.close();cleanup();}});
test('invalid persisted queue releases workspace lock when initialization fails',()=>{const {dir,store,cleanup}=setup();store.setEnrichmentJobs('invalid-shape' as never);store.close();try{assert.throws(()=>createApp(dir));assert.throws(()=>createApp(dir),e=>e instanceof Error&&!e.message.includes('already'));}finally{cleanup();}});
