import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Store} from '../server/store';
import {applyStockOperation,saveStockRecord,convertBulkToSerialized} from '../server/inventory';
import {commissionPCRecord,decommissionPC,savePCRecord} from '../server/pc-lifecycle';
import {stockCounts,fleetPicklist,overdueReservations,installedConfiguration,commissioningDrift,planDifferences} from '../shared/inventory';

function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bench-operations-'));const store=new Store(dir);const receive=(id:string,componentId='ram',quantity=5)=>{const s=saveStockRecord({id,componentId,tracking:'bulk',serial:'',assetTag:id,quantity,location:'Shelf A',condition:'Serviceable',notes:'',allocations:[],history:[]},store.db);store.replace('inventory',[...store.db.inventory,s]);return s;};const act=(id:string,input:unknown)=>{const result=applyStockOperation(store.db.inventory.find(s=>s.id===id)!,input,store.db);store.replace('inventory',[...store.db.inventory.map(s=>s.id===id?result.stock:s),...(result.additionalStock?[result.additionalStock]:[])]);return result;};return {store,receive,act,cleanup:()=>fs.rmSync(dir,{recursive:true,force:true})};}

test('failed bulk removal creates a quarantined destination atomically while preserving healthy installations',()=>{
 const {store,receive,act,cleanup}=setup();try{receive('lot');let {stock}=act('lot',{action:'install',pcId:'pc-01',quantity:3});const originalId=stock.allocations[0].id;const result=act('lot',{action:'remove',allocationId:originalId,quantity:1,disposition:'Repair',destinationLocation:'Repair cabinet',notes:'Failed memory'});assert.equal(result.stock.quantity,4);assert.equal(result.stock.condition,'Serviceable');assert.equal(result.stock.allocations[0].quantity,2);assert.equal(stockCounts(result.stock).available,2);assert.equal(result.additionalStock?.quantity,1);assert.equal(result.additionalStock?.condition,'Repair');assert.equal(stockCounts(result.additionalStock!).available,0);assert.equal(result.additionalStock?.history[0].sourceStockId,'lot');assert.equal(result.stock.history.find(e=>e.action==='remove')?.targetStockId,result.additionalStock?.id);assert.equal(new Store(store.dir).db.inventory.reduce((n,s)=>n+s.quantity,0),5);}finally{cleanup();}
});

test('partial reserved installations retain explicit reservation lineage and expiry does not free stock',()=>{
 const {store,receive,act,cleanup}=setup();try{receive('lot');let {stock}=act('lot',{action:'reserve',pcId:'pc-01',quantity:4,owner:'Lab engineer',workOrder:'WO-4',expiresAt:'2020-01-01T00:00:00.000Z'});const reservationId=stock.allocations[0].id;({stock}=act('lot',{action:'install-reserved',allocationId:reservationId,quantity:2}));assert.equal(stock.history.at(-1)?.sourceAllocationId,reservationId);assert.notEqual(stock.history.at(-1)?.allocationId,reservationId);assert.equal(stock.allocations.find(a=>a.state==='installed')?.workOrder,'WO-4');assert.equal(overdueReservations(store.db).length,1);assert.equal(stockCounts(stock).available,1);act('lot',{action:'release',allocationId:reservationId,quantity:2});assert.equal(overdueReservations(store.db).length,0);assert.equal(stockCounts(store.db.inventory[0]).available,3);}finally{cleanup();}
});

test('bulk serialization conserves stock and duplicate unit identities reject the complete transaction',()=>{
 const {store,receive,act,cleanup}=setup();try{receive('lot');act('lot',{action:'reserve',pcId:'pc-01',quantity:2});let conversion=convertBulkToSerialized(store.db.inventory[0],{units:[{serial:'RAM-1',assetTag:'A-1'},{serial:'RAM-2',assetTag:'A-2'}],notes:'Scanned identities'},store.db);store.replace('inventory',[conversion.source,...conversion.targets]);assert.equal(store.db.inventory.reduce((n,s)=>n+s.quantity,0),5);assert.equal(conversion.source.allocations[0].quantity,2);assert.equal(conversion.targets[0].history[0].sourceStockId,'lot');const before=JSON.stringify(store.db.inventory);conversion=convertBulkToSerialized(store.db.inventory[0],{units:[{serial:'RAM-1',assetTag:'A-3'}],notes:'Duplicate test'},store.db);assert.throws(()=>store.replace('inventory',[conversion.source,...store.db.inventory.slice(1),...conversion.targets]),/Duplicate serial/);assert.equal(JSON.stringify(store.db.inventory),before);}finally{cleanup();}
});

test('fleet picklist never assigns the same free units to several PCs',()=>{
 const {store,receive,cleanup}=setup();try{receive('lot');const template=structuredClone(store.db.configurations[0]);template.placements=[{id:'ram-demand',componentId:'ram',quantity:4,role:'general',mount:'auto',slotId:'',group:''}];store.replace('configurations',store.db.configurations.map(c=>c.id===template.id?template:c));store.replace('pcs',[...store.db.pcs,{...store.db.pcs[0],id:'pc-second',name:'Second PC'}]);const rows=fleetPicklist(store.db);assert.equal(rows.reduce((n,r)=>n+r.pick,0),5);assert.equal(rows.reduce((n,r)=>n+r.shortage,0),3);}finally{cleanup();}
});

test('commissioned snapshots preserve hardware identities and acceptance versions; decommission safely disposes stock',()=>{
 const {store,receive,act,cleanup}=setup();try{const config=store.db.configurations[0];for(const p of config.placements){receive(`stock-${p.id}`,p.componentId,p.quantity);act(`stock-${p.id}`,{action:'install',pcId:'pc-01',quantity:p.quantity,plannedPlacementId:p.id});}let pc=commissionPCRecord(store.db.pcs[0],{by:'Engineer',checks:['Boot checked','Equipment checked'],notes:'Accepted'},store.db);assert.equal(pc.snapshots?.length,1);assert.equal(pc.snapshot?.installedStock?.length,config.placements.length);assert.equal(commissioningDrift(pc,store.db),false);store.replace('pcs',store.db.pcs.map(p=>p.id===pc.id?pc:p));pc=savePCRecord({...pc,software:{os:'New OS image'}},store.db);assert.equal(commissioningDrift(pc,store.db),true);store.replace('pcs',store.db.pcs.map(p=>p.id===pc.id?pc:p));pc=commissionPCRecord(pc,{by:'Engineer',checks:['OS tested'],notes:'Reaccepted'},store.db);assert.equal(pc.snapshots?.length,2);assert.equal(pc.snapshots?.[0].configuration.software?.os,undefined);store.replace('pcs',store.db.pcs.map(p=>p.id===pc.id?pc:p));const retired=decommissionPC(pc,{disposition:'Repair',location:'Repair bench',notes:'Retiring controller'},store.db);assert.equal(retired.pcs.find(p=>p.id===pc.id)?.lifecycle,'Retired');assert.equal(retired.inventory.flatMap(s=>s.allocations).filter(a=>a.pcId===pc.id).length,0);assert.equal(retired.inventory.reduce((n,s)=>n+s.quantity,0),store.db.inventory.reduce((n,s)=>n+s.quantity,0));assert.equal(retired.inventory.filter(s=>s.condition==='Repair').reduce((n,s)=>n+s.quantity,0),config.placements.reduce((n,p)=>n+p.quantity,0));assert.throws(()=>savePCRecord({...pc,lifecycle:'Retired'},store.db),/Remove installed/);}finally{cleanup();}
});

test('equipment port instances map across serialized installations of one planned card line',()=>{
 const {store,cleanup}=setup();try{const db=structuredClone(store.db),pc=db.pcs[0];pc.buildSettings!.portMappings=[{connectionId:'camera',requirementId:'network',placementId:'network-line',instance:1,portId:'lan'}];for(let i=0;i<2;i++){let stock=saveStockRecord({id:`net-${i}`,componentId:'daq',tracking:'serialized',serial:`N-${i}`,assetTag:'',quantity:1,location:'',condition:'Serviceable',notes:'',allocations:[],history:[]},db);const plan={id:'network-line',componentId:'daq',quantity:2,role:'general' as const,mount:'auto' as const,slotId:'',group:''};db.configurations.find(c=>c.id===pc.configurationId)!.placements=[plan];stock=applyStockOperation(stock,{action:'install',pcId:pc.id,quantity:1,plannedPlacementId:plan.id},db).stock;db.inventory.push(stock);}const actual=installedConfiguration(pc,db);assert.equal(actual.portMappings?.[0].placementId,db.inventory[1].allocations[0].id);assert.equal(actual.portMappings?.[0].instance,0);assert.equal(actual.placements[0].adapterPlacementId,'');}finally{cleanup();}
});

test('planned drift includes group, software and controller settings without empty-field noise',()=>{
 const {store,cleanup}=setup();try{const db=structuredClone(store.db),pc=db.pcs[0],cfg=db.configurations.find(c=>c.id===pc.configurationId)!;cfg.placements=[];pc.buildSettings={systemId:cfg.systemId,storage:structuredClone(cfg.storage),notes:'',software:{os:'',bios:'',drivers:{},firmware:{}},portMappings:[]};assert.deepEqual(planDifferences(pc,db),[]);cfg.storage.groups=[{id:'science',name:'Science data',raid:'mirror',controllerPlacementId:'controller'}];assert.ok(planDifferences(pc,db).some(d=>d.includes('storage groups')));pc.buildSettings.storage=structuredClone(cfg.storage);pc.software={os:'New image'};assert.ok(planDifferences(pc,db).some(d=>d.includes('software')));}finally{cleanup();}
});

test('default-group drives cannot satisfy a named-group placement and inherited software remains recorded',()=>{
 const {store,receive,act,cleanup}=setup();try{const cfg=structuredClone(store.db.configurations[0]);cfg.placements=[{id:'drive',componentId:'ssd',quantity:1,role:'data',mount:'auto',slotId:'',group:''}];store.replace('configurations',store.db.configurations.map(c=>c.id===cfg.id?cfg:c));receive('ssd','ssd',1);act('ssd',{action:'install',pcId:'pc-01',quantity:1,plannedPlacementId:'drive',group:'science'});assert.ok(planDifferences(store.db.pcs[0],store.db).some(d=>d.includes('missing or placed differently')));const pc=structuredClone(store.db.pcs[0]);pc.buildSettings!.software={os:'Captured OS',drivers:{ssd:'1.2'}};delete pc.software;assert.deepEqual(installedConfiguration(pc,store.db).software,pc.buildSettings!.software);}finally{cleanup();}
});

test('decommissioning actor and reservation metadata remain in the ledger after allocations disappear',()=>{
 const {store,receive,act,cleanup}=setup();try{receive('lot');act('lot',{action:'reserve',pcId:'pc-01',quantity:2,owner:'Lab engineer',workOrder:'WO-42',dueAt:'2030-01-01T00:00:00.000Z'});const next=decommissionPC(store.db.pcs[0],{disposition:'Quarantined',location:'Shelf B',notes:'Cancelled build',actor:'Technician'},store.db);const release=next.inventory[0].history.find(e=>e.action==='release')!;assert.equal(release.actor,'Technician');assert.match(release.notes,/Lab engineer/);assert.match(release.notes,/WO-42/);assert.equal(next.inventory[0].allocations.length,0);}finally{cleanup();}
});
