import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Store,encodeCSV,decodeCSV,encodeMovements} from '../server/store';
import {lockWorkspace} from '../server/persistence';
import {saveStockRecord,applyStockAction} from '../server/inventory';
import {DatabaseSync} from 'node:sqlite';
import {seed} from '../server/seed';
import {collections} from '../server/store';
import {parse} from 'csv-parse/sync';
function persistedState(dir:string){const store=new Store(dir);try{return structuredClone(store.db);}finally{store.close();}}
function workspace(run:(store:Store,dir:string)=>void){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bench-review-'));const store=new Store(dir);try{run(store,dir);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}}
test('collection write limits preserve restartable files',()=>workspace((s,dir)=>{const original=structuredClone(s.db);const rows=Array.from({length:10001},(_,i)=>({...s.db.pcs[0],id:`pc-${i}`}));assert.throws(()=>s.replace('pcs',rows),/10,000/);assert.deepEqual(s.db,original);assert.deepEqual(persistedState(dir),s.db);}));
test('ordinary replacement cannot rewrite allocated physical stock identity',()=>workspace(s=>{let stock=saveStockRecord({id:'stock',componentId:'ram',tracking:'serialized',serial:'ABC',assetTag:'',quantity:1,location:'Shelf',condition:'Serviceable',notes:'',allocations:[],history:[]},s.db);stock=applyStockAction(stock,{action:'install',pcId:'pc-01',quantity:1},s.db);s.replace('inventory',[stock]);assert.throws(()=>s.replace('inventory',[{...stock,componentId:'cpu'}]),/identity/);assert.throws(()=>s.replace('inventory',[{...stock,tracking:'bulk',serial:''}]),/identity/);assert.equal(s.db.inventory[0].componentId,'ram');}));
test('workspace lock excludes second server and releases idempotently',()=>workspace((_s,dir)=>{const release=lockWorkspace(dir);assert.throws(()=>lockWorkspace(dir),/already open/);release();release();lockWorkspace(dir)();}));
test('validated whole workspace restore creates safety snapshot and survives restart',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.pcs=[];const revision=s.revision;const invalid={...next,components:[]};assert.throws(()=>s.restore(invalid),/not found/);assert.deepEqual(s.db,original);const filename=s.restore(next);assert.deepEqual(JSON.parse(fs.readFileSync(filename,'utf8')),original);assert.notEqual(s.revision,revision);assert.deepEqual(persistedState(dir),next);assert.throws(()=>s.validateBackup({...next,inventory:undefined}),/missing inventory/);}));
test('legacy CSV migrates once without replacing the originals',()=>workspace((s,dir)=>{s.close();for(const filename of ['workbench.sqlite','workbench.sqlite-wal','workbench.sqlite-shm'])if(fs.existsSync(path.join(dir,filename)))fs.unlinkSync(path.join(dir,filename));const initial=structuredClone(seed);initial.pcs[0].location='Legacy shelf';for(const collection of collections)fs.writeFileSync(path.join(dir,`${collection}.csv`),encodeCSV(collection,initial[collection]));const original=fs.readFileSync(path.join(dir,'pcs.csv'),'utf8');const migrated=new Store(dir);assert.equal(migrated.db.pcs[0].location,'Legacy shelf');migrated.replace('pcs',migrated.db.pcs.map(pc=>({...pc,location:'SQLite shelf'})));migrated.close();assert.equal(fs.readFileSync(path.join(dir,'pcs.csv'),'utf8'),original);fs.writeFileSync(path.join(dir,'pcs.csv'),'invalid external edit');const restarted=new Store(dir);assert.equal(restarted.db.pcs[0].location,'SQLite shelf');restarted.close();}));
test('legacy pending restore journal is imported atomically on first SQLite initialization',()=>workspace((s,dir)=>{const next=structuredClone(s.db);next.pcs[0].location='Journal recovery';s.close();for(const filename of ['workbench.sqlite','workbench.sqlite-wal','workbench.sqlite-shm'])if(fs.existsSync(path.join(dir,filename)))fs.unlinkSync(path.join(dir,filename));fs.writeFileSync(path.join(dir,'.restore-journal.json'),JSON.stringify(next));const recovered=new Store(dir);assert.equal(recovered.db.pcs[0].location,'Journal recovery');recovered.close();assert.equal(fs.existsSync(path.join(dir,'.restore-journal.json')),true);}));
test('spreadsheet exports neutralize formulas while raw exports preserve round trips',()=>workspace(s=>{s.db.pcs[0].name='=HYPERLINK("https://example.com","x")';const raw=parse(encodeCSV('pcs',s.db.pcs),{columns:true}) as Record<string,string>[];const safe=parse(encodeCSV('pcs',s.db.pcs,true),{columns:true}) as Record<string,string>[];assert.equal(raw[0].name,s.db.pcs[0].name);assert.equal(safe[0].name,"'"+s.db.pcs[0].name);const stock=saveStockRecord({id:'stock',componentId:'ram',tracking:'bulk',serial:'',assetTag:'@formula',quantity:1,location:'Shelf',condition:'Serviceable',notes:'=cmd',allocations:[],history:[]},s.db);s.db.inventory=[stock];assert.equal((parse(encodeMovements(s.db,true),{columns:true}) as Record<string,string>[])[0].assetTag,"'@formula");}));
test('normal saves retain bounded automatic recovery snapshots',()=>workspace((s,dir)=>{for(let i=0;i<12;i++)s.replace('pcs',s.db.pcs.map(p=>({...p,location:`location ${i}`})));const files=fs.readdirSync(path.join(dir,'backups')).filter(f=>f.startsWith('rolling-'));assert.equal(files.length,10);const previous=JSON.parse(fs.readFileSync(path.join(dir,'backups',files.sort().at(-1)!),'utf8'));assert.equal(previous.pcs[0].location,'location 10');}));
test('failed SQLite restore rolls back all collections and live state',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.pcs[0].location='Should roll back';next.components[0].name='Should also roll back';const persist=s.persist.bind(s);let failed=false;s.persist=(collection,rows)=>{if(collection==='configurations'&&!failed){failed=true;throw Error('Simulated disk failure');}persist(collection,rows);};assert.throws(()=>s.restore(next),/Simulated disk/);assert.deepEqual(s.db,original);assert.deepEqual(persistedState(dir),original);assert.equal(fs.existsSync(path.join(dir,'.restore-journal.json')),false);}));
test('extended inventory procurement and repair metadata round trips across restart',()=>workspace((s,dir)=>{const stock=saveStockRecord({id:'metadata-lot',componentId:'ram',tracking:'bulk',serial:'',assetTag:'LOT',quantity:8,location:'Shelf',condition:'Repair',notes:'',supplier:'Vendor',purchaseOrder:'PO-42',reorderLevel:4,repairReference:'Repair-5',supplierReturnReference:'RMA-9',allocations:[],history:[]},s.db);s.replace('inventory',[stock]);assert.deepEqual(persistedState(dir).inventory,s.db.inventory);}));

test('failed collection write rolls back SQLite without changing memory or requiring recovery',()=>workspace((s,dir)=>{const original=structuredClone(s.db),rows=s.db.pcs.map(p=>({...p,location:'Uncommitted'}));const persist=s.persist.bind(s);s.persist=(collection,data)=>{persist(collection,data);if(collection==='pcs')throw Error('Injected SQLite write failure');};assert.throws(()=>s.replace('pcs',rows),/Injected SQLite/);assert.equal(s.recoveryRequired,false);assert.deepEqual(s.db,original);const restarted=new Store(dir);assert.deepEqual(restarted.db,original);restarted.close();}));
test('SQLite rollback uncertainty freezes writes until restart',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.components[0].name='Uncommitted state';const sqlite=(s as unknown as {sqlite:DatabaseSync}).sqlite;const exec=sqlite.exec.bind(sqlite);const injection=mock.method(sqlite,'exec',(sql:string)=>{exec(sql);if(sql==='ROLLBACK')throw Error('Injected rollback uncertainty');});const persist=s.persist.bind(s);s.persist=(collection,rows)=>{if(collection==='configurations')throw Error('Injected restore failure');persist(collection,rows);};try{assert.throws(()=>s.restore(next),/rollback could not be confirmed/);assert.equal(s.recoveryRequired,true);assert.deepEqual(s.db,original);assert.throws(()=>s.replace('pcs',original.pcs),/restart the server/);}finally{injection.mock.restore();}const restarted=new Store(dir);assert.deepEqual(restarted.db,original);restarted.close();}));
test('CSV replacements and whole-workspace restores reject allocations on retired PCs',()=>workspace(s=>{const stock=saveStockRecord({id:'retirement-unit',componentId:'ram',tracking:'serialized',serial:'RET1',assetTag:'',quantity:1,location:'Shelf',condition:'Serviceable',notes:'',allocations:[],history:[]},s.db);const allocated=applyStockAction(stock,{action:'reserve',pcId:'pc-01',quantity:1},s.db);s.replace('inventory',[allocated]);const retired=s.db.pcs.map(pc=>({...pc,lifecycle:'Retired' as const}));assert.throws(()=>s.replace('pcs',retired),/retired PC/);const backup=structuredClone(s.db);backup.pcs=retired;assert.throws(()=>s.restore(backup),/retired PC/);s.replace('inventory',[stock]);s.replace('pcs',retired);assert.throws(()=>s.replace('inventory',[allocated]),/retired PC/);assert.equal(s.db.inventory[0].allocations.length,0);}));

test('SQLite uses WAL, FULL synchronization, and database-level foreign key checks',()=>workspace((s)=>{const sqlite=(s as unknown as {sqlite:DatabaseSync}).sqlite;assert.equal(sqlite.prepare('PRAGMA journal_mode').get()?.journal_mode,'wal');assert.equal(sqlite.prepare('PRAGMA synchronous').get()?.synchronous,2);assert.equal(sqlite.prepare('PRAGMA foreign_keys').get()?.foreign_keys,1);assert.throws(()=>sqlite.prepare('INSERT INTO record_references VALUES(?,?,?,?,?)').run('pcs','missing-pc','test','components','missing-component'),/FOREIGN KEY/);assert.deepEqual(sqlite.prepare('PRAGMA foreign_key_check').all(),[]);}));
test('legacy five-collection JSON restores include empty requirement and location collections',()=>workspace(s=>{const old=structuredClone(s.db) as Partial<typeof s.db>;delete old.requirementsSets;delete old.installationLocations;const restored=s.validateBackup(old);assert.deepEqual(restored.requirementsSets,[]);assert.deepEqual(restored.installationLocations,[]);}));
test('stale direct SQLite connections cannot overwrite another committed writer',()=>workspace((s,dir)=>{const second=new Store(dir);s.replace('pcs',s.db.pcs.map(p=>({...p,location:'First writer'})));assert.throws(()=>second.replace('pcs',second.db.pcs.map(p=>({...p,location:'Stale writer'}))),/another connection/);assert.equal(second.recoveryRequired,false);second.close();const reopened=new Store(dir);assert.equal(reopened.db.pcs[0].location,'First writer');reopened.close();}));

test('requirement revisions and hierarchical locations persist with protected references',()=>workspace((s,dir)=>{const version={revision:1,at:'2026-10-08T00:00:00Z',name:'Instrument requirement v1',description:'',connections:[],constraints:{requiredComponents:[{componentId:'ram',quantity:1}]}};const requirements={id:'requirements',name:'Instrument requirements',description:'',versions:[version]};s.replace('requirementsSets',[requirements]);assert.throws(()=>s.replace('requirementsSets',[{...requirements,versions:[{...version,name:'Changed history'}]}]),/immutable/);s.replace('requirementsSets',[{...requirements,versions:[version,{...version,revision:2,name:'Revision two'}]}]);const root={id:'site',name:'Site',kind:'Site' as const,parentId:'',requirementSetId:'',requirementRevision:0,targetConfigurationId:'',notes:''};const bench={...root,id:'bench',name:'Bench',kind:'Bench' as const,parentId:'site',requirementSetId:'requirements',requirementRevision:1,requirementSnapshot:version,targetConfigurationId:'imaging'};s.replace('installationLocations',[root,bench]);assert.deepEqual(decodeCSV('installationLocations',encodeCSV('installationLocations',s.db.installationLocations)),s.db.installationLocations);s.replace('pcs',s.db.pcs.map(pc=>({...pc,installationLocationId:'bench'})));assert.throws(()=>s.replace('pcs',s.db.pcs.map(pc=>({...pc,installationLocationId:'site'}))),/Bench or System/);assert.throws(()=>s.replace('installationLocations',[{...root,parentId:'bench'},bench]),/cycle/);assert.throws(()=>s.replace('installationLocations',[bench]),/parent.*not found/);assert.throws(()=>s.replace('requirementsSets',[]),/not found/);assert.throws(()=>s.replace('installationLocations',[root,{...bench,requirementRevision:3}]),/revision not found/);const restarted=new Store(dir);assert.deepEqual(restarted.db,s.db);restarted.close();}));
