import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Store,encodeCSV,encodeMovements} from '../server/store';
import {lockWorkspace} from '../server/persistence';
import {saveStockRecord,applyStockAction} from '../server/inventory';
import {parse} from 'csv-parse/sync';
function workspace(run:(store:Store,dir:string)=>void){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bench-review-'));try{run(new Store(dir),dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('collection write limits preserve restartable files',()=>workspace((s,dir)=>{const original=fs.readFileSync(path.join(dir,'pcs.csv'),'utf8');const rows=Array.from({length:10001},(_,i)=>({...s.db.pcs[0],id:`pc-${i}`}));assert.throws(()=>s.replace('pcs',rows),/10,000/);assert.equal(fs.readFileSync(path.join(dir,'pcs.csv'),'utf8'),original);assert.deepEqual(new Store(dir).db,s.db);}));
test('ordinary replacement cannot rewrite allocated physical stock identity',()=>workspace(s=>{let stock=saveStockRecord({id:'stock',componentId:'ram',tracking:'serialized',serial:'ABC',assetTag:'',quantity:1,location:'Shelf',condition:'Serviceable',notes:'',allocations:[],history:[]},s.db);stock=applyStockAction(stock,{action:'install',pcId:'pc-01',quantity:1},s.db);s.replace('inventory',[stock]);assert.throws(()=>s.replace('inventory',[{...stock,componentId:'cpu'}]),/identity/);assert.throws(()=>s.replace('inventory',[{...stock,tracking:'bulk',serial:''}]),/identity/);assert.equal(s.db.inventory[0].componentId,'ram');}));
test('workspace lock excludes second server and releases idempotently',()=>workspace((_s,dir)=>{const release=lockWorkspace(dir);assert.throws(()=>lockWorkspace(dir),/already open/);release();release();lockWorkspace(dir)();}));
test('validated whole workspace restore creates safety snapshot and survives restart',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.pcs=[];const revision=s.revision;const invalid={...next,components:[]};assert.throws(()=>s.restore(invalid),/not found/);assert.deepEqual(s.db,original);const filename=s.restore(next);assert.deepEqual(JSON.parse(fs.readFileSync(filename,'utf8')),original);assert.notEqual(s.revision,revision);assert.deepEqual(new Store(dir).db,next);assert.throws(()=>s.validateBackup({...next,inventory:undefined}),/missing inventory/);}));
test('interrupted restore is completed from durable journal at startup',()=>workspace((s,dir)=>{const next=structuredClone(s.db);next.pcs[0].location='Restored location';fs.writeFileSync(path.join(dir,'.restore-journal.json'),JSON.stringify(next));assert.deepEqual(new Store(dir).db,next);assert.equal(fs.existsSync(path.join(dir,'.restore-journal.json')),false);}));
test('spreadsheet exports neutralize formulas while raw exports preserve round trips',()=>workspace(s=>{s.db.pcs[0].name='=HYPERLINK("https://example.com","x")';const raw=parse(encodeCSV('pcs',s.db.pcs),{columns:true}) as Record<string,string>[];const safe=parse(encodeCSV('pcs',s.db.pcs,true),{columns:true}) as Record<string,string>[];assert.equal(raw[0].name,s.db.pcs[0].name);assert.equal(safe[0].name,"'"+s.db.pcs[0].name);const stock=saveStockRecord({id:'stock',componentId:'ram',tracking:'bulk',serial:'',assetTag:'@formula',quantity:1,location:'Shelf',condition:'Serviceable',notes:'=cmd',allocations:[],history:[]},s.db);s.db.inventory=[stock];assert.equal((parse(encodeMovements(s.db,true),{columns:true}) as Record<string,string>[])[0].assetTag,"'@formula");}));
test('normal saves retain bounded automatic recovery snapshots',()=>workspace((s,dir)=>{for(let i=0;i<12;i++)s.replace('pcs',s.db.pcs.map(p=>({...p,location:`location ${i}`})));const files=fs.readdirSync(path.join(dir,'backups')).filter(f=>f.startsWith('rolling-'));assert.equal(files.length,10);const previous=JSON.parse(fs.readFileSync(path.join(dir,'backups',files.sort().at(-1)!),'utf8'));assert.equal(previous.pcs[0].location,'location 10');}));
test('failed multi-file restore rolls back the disk and live state',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.pcs[0].location='Should roll back';next.components[0].name='Should also roll back';const persist=s.persist.bind(s);let failed=false;s.persist=(collection,rows)=>{if(collection==='configurations'&&!failed){failed=true;throw Error('Simulated disk failure');}persist(collection,rows);};assert.throws(()=>s.restore(next),/Simulated disk/);assert.deepEqual(s.db,original);assert.deepEqual(new Store(dir).db,original);assert.equal(fs.existsSync(path.join(dir,'.restore-journal.json')),false);}));
test('extended inventory procurement and repair metadata round trips across restart',()=>workspace((s,dir)=>{const stock=saveStockRecord({id:'metadata-lot',componentId:'ram',tracking:'bulk',serial:'',assetTag:'LOT',quantity:8,location:'Shelf',condition:'Repair',notes:'',supplier:'Vendor',purchaseOrder:'PO-42',reorderLevel:4,repairReference:'Repair-5',supplierReturnReference:'RMA-9',allocations:[],history:[]},s.db);s.replace('inventory',[stock]);assert.deepEqual(new Store(dir).db.inventory,s.db.inventory);}));

test('post-rename directory sync failure freezes edits until restart',()=>workspace((s,dir)=>{const original=structuredClone(s.db),rows=s.db.pcs.map(p=>({...p,location:'Committed but unconfirmed'}));const sync=fs.fsyncSync.bind(fs);const injection=mock.method(fs,'fsyncSync',(fd:number)=>{if(fs.fstatSync(fd).isDirectory()&&fs.readFileSync(path.join(dir,'pcs.csv'),'utf8').includes('Committed but unconfirmed'))throw Error('Injected directory fsync failure');return sync(fd);});try{assert.throws(()=>s.replace('pcs',rows),/restart the server/);assert.equal(s.recoveryRequired,true);assert.deepEqual(s.db,original);assert.throws(()=>s.replace('pcs',original.pcs),/restart the server/);assert.throws(()=>s.restore(original),/restart the server/);}finally{injection.mock.restore();}assert.equal(new Store(dir).db.pcs[0].location,'Committed but unconfirmed');}));
test('failed restore rollback freezes writes and leaves a recoverable journal',()=>workspace((s,dir)=>{const original=structuredClone(s.db),next=structuredClone(s.db);next.components[0].name='Intermediate disk state';next.pcs[0].location='Incomplete restore';const persist=s.persist.bind(s);let restoringFailed=false;s.persist=(collection,rows)=>{if(collection==='configurations'){restoringFailed=true;throw Error('Injected restore failure');}if(restoringFailed&&collection==='components')throw Error('Injected rollback failure');persist(collection,rows);};assert.throws(()=>s.restore(next),/rollback could not finish/);assert.equal(s.recoveryRequired,true);assert.deepEqual(s.db,original);assert.equal(fs.existsSync(path.join(dir,'.restore-journal.json')),true);assert.throws(()=>s.replace('pcs',original.pcs),/restart the server/);assert.deepEqual(new Store(dir).db,original);}));

test('CSV replacements and whole-workspace restores reject allocations on retired PCs',()=>workspace(s=>{const stock=saveStockRecord({id:'retirement-unit',componentId:'ram',tracking:'serialized',serial:'RET1',assetTag:'',quantity:1,location:'Shelf',condition:'Serviceable',notes:'',allocations:[],history:[]},s.db);const allocated=applyStockAction(stock,{action:'reserve',pcId:'pc-01',quantity:1},s.db);s.replace('inventory',[allocated]);const retired=s.db.pcs.map(pc=>({...pc,lifecycle:'Retired' as const}));assert.throws(()=>s.replace('pcs',retired),/retired PC/);const backup=structuredClone(s.db);backup.pcs=retired;assert.throws(()=>s.restore(backup),/retired PC/);s.replace('inventory',[stock]);s.replace('pcs',retired);assert.throws(()=>s.replace('inventory',[allocated]),/retired PC/);assert.equal(s.db.inventory[0].allocations.length,0);}));
