import { z } from 'zod';
import { categories, portKinds } from '../shared/types';
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/), str=z.string().max(10000), count=z.number().int().min(0).max(10000), quantity=z.number().int().min(1).max(32);
const optionalDate=z.union([z.iso.datetime(),z.literal('')]);
const condition=z.enum(['Serviceable','Quarantined','Repair','Retired']);
const raid=z.enum(['none','mirror','raid5','raid6','raid10']);
const mount=z.enum(['auto','internal','front-hot-swap','rear-sled']);
const pciVoltage=z.enum(['3.3V','5V','universal']);
const software=z.object({os:str.optional(),image:str.optional(),equipmentSoftware:str.optional(),equipmentConfiguration:str.optional(),bios:str.optional(),drivers:z.record(id,str).optional(),firmware:z.record(id,str).optional()}).strict();
const mappings=z.array(z.object({connectionId:id,requirementId:id,placementId:id,instance:count,portId:id}).strict()).max(1000);
const storage=z.object({raid,bootMirror:z.boolean(),groups:z.array(z.object({id,name:str,raid,controllerPlacementId:str.optional(),notes:str.optional()}).strict()).max(100).refine(g=>new Set(g.map(x=>x.id)).size===g.length,'Storage group IDs must be unique').optional()}).strict();
const binding={group:str.optional(),targetId:str.optional(),adapterPlacementId:str.optional(),controllerPlacementId:str.optional()};
const reservation={owner:str.default(''),workOrder:str.default(''),dueAt:optionalDate.default(''),expiresAt:optionalDate.default('')};
const slot=z.object({id,bus:z.enum(['PCI','PCIe']),physical:z.number().int().min(1).max(16),lanes:z.number().int().min(1).max(16),generation:z.number().int().min(1).max(7),position:z.number().int().min(1).max(32),bifurcationModes:z.array(str).max(20).optional(),pciVoltage:pciVoltage.optional(),pciBits:z.union([z.literal(32),z.literal(64)]).optional()}).strict();
const baySize=z.enum(['2.5','3.5','5.25']);
const specs=z.object({
 bayTargets:z.array(z.object({id,size:baySize}).strict()).max(1000).refine(t=>new Set(t.map(x=>x.id)).size===t.length,'Bay target IDs must be unique').optional(),baySize:baySize.optional(),bayUnits:z.number().int().min(1).max(32).optional(),sataPowerPlugs:count.optional(),
 ports:z.array(z.object({id,kind:z.enum(portKinds),connector:str.optional(),pinout:str.optional(),customType:str.optional(),protocol:str.optional(),speedMbps:z.number().nonnegative().optional(),powerW:z.number().nonnegative().optional(),isolated:z.boolean().optional()}).strict().superRefine((port,ctx)=>{if(port.kind==='Custom'&&!port.customType?.trim())ctx.addIssue({code:'custom',message:'Custom ports require a nonblank custom type'});})).max(1000).refine(p=>new Set(p.map(x=>x.id)).size===p.length,'Port IDs must be unique').optional(),
 driveTargets:z.array(z.object({id,mount,driveSizes:z.array(str).optional(),interfaces:z.array(str).optional(),m2Lengths:z.array(count).optional(),hotSwap:z.boolean().optional(),bootable:z.boolean().optional()}).strict()).max(1000).refine(t=>new Set(t.map(x=>x.id)).size===t.length,'Drive target IDs must be unique').optional(),
 laneRules:z.array(z.object({id,slots:z.array(id).max(32),maxLanes:count.optional(),exclusive:z.boolean().optional(),disableM2Slots:count.optional(),disableSataPorts:count.optional()}).strict()).max(100).optional(),
 pciVoltage:pciVoltage.optional(),pciBits:z.union([z.literal(32),z.literal(64)]).optional(),bifurcationMode:str.optional(),supportedOS:z.array(str).max(100).optional(),requiredDriver:str.optional(),requiredFirmware:str.optional(),bootable:z.boolean().optional(),hotPlug:z.boolean().optional(),
 socket:str.optional(),formFactor:str.optional(),supportedForms:z.array(str).max(20).optional(),memoryType:str.optional(),dimmSlots:count.optional(),maxMemoryGb:count.optional(),capacityGb:z.number().min(0).max(10000000).optional(),
 slots:z.array(slot).max(32).refine(s=>new Set(s.map(x=>x.id)).size===s.length,'Slot IDs must be unique').refine(s=>new Set(s.map(x=>x.position)).size===s.length,'Slot positions must be unique').optional(),slotBus:z.enum(['PCI','PCIe']).optional(),slotWidth:z.number().int().min(1).max(16).optional(),requiredLanes:z.number().int().min(1).max(16).optional(),minGeneration:z.number().int().min(1).max(7).optional(),bracketWidth:z.number().int().min(1).max(8).optional(),
 lengthMm:count.optional(),heightMm:count.optional(),widthMm:count.optional(),maxCardLengthMm:count.optional(),maxCardHeightMm:count.optional(),maxCoolerHeightMm:count.optional(),rearSlots:count.optional(),bays25:count.optional(),bays35:count.optional(),bays525:count.optional(),hotSwapBays:count.optional(),sataPorts:count.optional(),m2Slots:count.optional(),m2Lengths:z.array(count).max(20).optional(),sataPower:count.optional(),
 usbA:count.optional(),usbC:count.optional(),ethernet:count.optional(),powerW:count.optional(),capacityW:count.optional(),driveInterface:z.enum(['SATA','NVMe']).optional(),driveSize:z.enum(['2.5','3.5','M.2']).optional(),m2Length:count.optional(),sledDrives:count.optional(),requiresBifurcation:z.boolean().optional(),bifurcation:z.boolean().optional(),sledHotSwap:z.boolean().optional(),supportsSockets:z.array(str).max(20).optional(),notes:str.optional()
}).strict().superRefine((spec,ctx)=>{for(const rule of spec.laneRules||[])for(const slotId of rule.slots)if(!spec.slots?.some(slot=>slot.id===slotId))ctx.addIssue({code:'custom',message:`Lane rule ${rule.id}: slot ${slotId} does not exist`});if(spec.laneRules&&new Set(spec.laneRules.map(r=>r.id)).size!==spec.laneRules.length)ctx.addIssue({code:'custom',message:'Lane rule IDs must be unique'});});
const componentSchema=z.object({id,name:z.string().min(1).max(200),category:z.enum(categories),manufacturer:str,specs,source:str,verified:z.boolean()}).strict();
const systemSchema=z.object({id,name:z.string().min(1).max(200),location:str,description:str,connections:z.array(z.object({id,name:z.string().min(1).max(200),usbA:count,usbC:count,ethernet:count,notes:str,requirements:z.array(z.object({id,kind:z.enum(portKinds),quantity:count,connector:str.optional(),pinout:str.optional(),customType:str.optional(),protocol:str.optional(),minSpeedMbps:z.number().nonnegative().optional(),minPowerW:z.number().nonnegative().optional(),isolated:z.boolean().optional()}).strict().superRefine((port,ctx)=>{if(port.kind==='Custom'&&!port.customType?.trim())ctx.addIssue({code:'custom',message:'Custom ports require a nonblank custom type'});})).max(1000).refine(r=>new Set(r.map(x=>x.id)).size===r.length,'Requirement IDs must be unique').optional()}).strict()).max(200).refine(c=>new Set(c.map(x=>x.id)).size===c.length,'Connection IDs must be unique')}).strict();
export const requirementVersionSchema=z.object({revision:z.number().int().min(1).max(1000000),at:z.iso.datetime(),name:z.string().min(1).max(200),description:str,connections:systemSchema.shape.connections,constraints:z.object({minMemoryGb:z.number().nonnegative().max(10000000).optional(),minDataGb:z.number().nonnegative().max(1000000000).optional(),minBootGb:z.number().nonnegative().max(1000000000).optional(),minScientificCards:count.optional(),requiredComponents:z.array(z.object({componentId:id,quantity:count}).strict()).max(10000).refine(rows=>new Set(rows.map(r=>r.componentId)).size===rows.length,'Required component IDs must be unique').optional()}).strict().optional(),software:software.optional(),storage:storage.optional()}).strict();
const requirementBinding={requirementSetId:z.union([id,z.literal('')]).optional(),requirementRevision:z.number().int().min(0).max(1000000).optional(),requirementSnapshot:requirementVersionSchema.optional()};
const configurationBase=z.object({...requirementBinding,id,name:z.string().min(1).max(200),description:str,systemId:z.union([id,z.literal('')]),status:z.enum(['Draft','In review','Approved']),updatedAt:z.iso.datetime(),placements:z.array(z.object({id,componentId:id,quantity,slotId:str,role:z.enum(['boot','data','general']),mount:z.enum(['auto','internal','front-hot-swap','rear-sled']),...binding,group:str}).strict()).max(200).refine(p=>new Set(p.map(x=>x.id)).size===p.length,'Placement IDs must be unique'),storage,notes:str,software:software.optional(),portMappings:mappings.optional(),revision:count.optional(),approvalSnapshot:z.object({at:z.iso.datetime(),components:z.array(componentSchema).max(10000),system:systemSchema.nullable()}).strict().optional()}).strict();
const approvalRecord=z.object({revision:count,at:z.iso.datetime(),configuration:configurationBase.omit({revision:true,approvalSnapshot:true}),components:z.array(componentSchema).max(10000),system:systemSchema.nullable()}).strict();
const configurationSchema=configurationBase.extend({approvalHistory:z.array(approvalRecord).max(1000).optional()});
const installedStock=z.array(z.object({stockId:id,componentId:id,serial:str,assetTag:str,allocationId:id,quantity,role:z.enum(['boot','data','general']),mount,slotId:str,group:str.optional(),targetId:str.optional()}).strict()).max(10000);
const installationSnapshot=z.object({locationId:id,path:str,requirementSetId:z.union([id,z.literal('')]),requirementRevision:z.number().int().min(0).max(1000000),targetConfigurationId:z.union([id,z.literal('')]),requirementSnapshot:requirementVersionSchema.optional()}).strict();
const snapshot=z.object({installation:installationSnapshot.optional(),at:z.iso.datetime(),configuration:configurationSchema,components:z.array(componentSchema).max(10000),system:systemSchema.nullable(),installedStock:installedStock.optional()}).strict();
export const schemas={requirementsSets:z.object({id,name:z.string().min(1).max(200),description:str,versions:z.array(requirementVersionSchema).max(1000).refine(versions=>new Set(versions.map(v=>v.revision)).size===versions.length,'Requirement revision numbers must be unique')}).strict(),installationLocations:z.object({id,name:z.string().min(1).max(200),kind:z.enum(['Site','Room','Bench','System']),parentId:z.union([id,z.literal('')]),requirementSetId:z.union([id,z.literal('')]),requirementRevision:z.number().int().min(0).max(1000000),targetConfigurationId:z.union([id,z.literal('')]),notes:str,requirementSnapshot:requirementVersionSchema.optional()}).strict(),components:componentSchema,systems:systemSchema,configurations:configurationSchema,
 pcs:z.object({installationLocationId:z.union([id,z.literal('')]).optional(),id,name:z.string().min(1).max(200),serial:str,location:str,configurationId:z.union([id,z.literal('')]),notes:str,buildSettings:z.object({...requirementBinding,systemId:z.union([id,z.literal('')]),storage,notes:str,software:software.optional(),portMappings:mappings.optional()}).strict().nullable().default(null),lifecycle:z.enum(['Planning','Building','Commissioned','In service','Maintenance','Parts only','Retired']).optional(),software:software.optional(),commissioning:z.object({at:z.iso.datetime(),by:str,checks:z.array(str).max(1000),notes:str}).strict().optional(),timeline:z.array(z.object({id,at:z.iso.datetime(),kind:str,summary:str,actor:str}).strict()).max(100000).optional(),snapshot:snapshot.optional(),snapshots:z.array(snapshot).max(1000).optional()}).strict(),
 inventory:z.object({id,componentId:id,tracking:z.enum(['serialized','bulk']),serial:str,assetTag:str,quantity:z.number().int().min(0).max(1000000),location:str,condition,notes:str,supplier:str.default(''),purchaseOrder:str.default(''),repairReference:str.default(''),supplierReturnReference:str.default(''),reorderLevel:count.default(0),
  allocations:z.array(z.object({id,pcId:id,quantity,state:z.enum(['reserved','installed']),plannedPlacementId:str,slotId:str,role:z.enum(['boot','data','general']),mount,...binding,...reservation,notes:str,createdAt:z.iso.datetime(),updatedAt:z.iso.datetime()}).strict()).max(10000),
  history:z.array(z.object({id,at:z.iso.datetime(),action:z.enum(['receive','adjust','edit','reserve','install','release','remove','configure','transfer-in','transfer-out']),quantity:z.number().int().min(-1000000).max(1000000),pcId:str,pcName:str,allocationId:str,sourceAllocationId:str.default(''),targetStockId:str.default(''),sourceStockId:str.default(''),actor:str.default(''),notes:str}).strict()).max(100000).refine(events=>new Set(events.map(e=>e.id)).size===events.length,'Duplicate movement IDs')
 }).strict().superRefine((stock,ctx)=>{if(stock.tracking==='serialized'&&(stock.quantity!==1||!stock.serial.trim()))ctx.addIssue({code:'custom',message:'Serialized stock needs a serial number and quantity 1'});if(stock.tracking==='bulk'&&stock.serial.trim())ctx.addIssue({code:'custom',message:'Bulk lots cannot have a unit serial number'});if(stock.allocations.reduce((n,a)=>n+a.quantity,0)>stock.quantity)ctx.addIssue({code:'custom',message:'Allocations exceed stock quantity'});if(new Set(stock.allocations.map(a=>a.id)).size!==stock.allocations.length)ctx.addIssue({code:'custom',message:'Duplicate allocation IDs'});if(stock.condition==='Retired'&&stock.allocations.length)ctx.addIssue({code:'custom',message:'Release reservations and remove installations before retiring stock'});})
};
export type Collection=keyof typeof schemas;
export const stockActionSchema=z.discriminatedUnion('action',[
 z.object({action:z.enum(['reserve','install']),pcId:id,quantity,plannedPlacementId:str.default(''),slotId:str.optional(),role:z.enum(['boot','data','general']).optional(),mount:mount.optional(),...binding,...reservation,notes:str.default('')}).strict(),
 z.object({action:z.enum(['install-reserved','release','remove']),allocationId:id,quantity,notes:str.default(''),destinationLocation:str.optional(),disposition:condition.optional(),actor:str.optional()}).strict(),
 z.object({action:z.literal('configure'),allocationId:id,slotId:str,role:z.enum(['boot','data','general']),mount,...binding,...reservation,notes:str.default('')}).strict()
]);
export type StockAction=z.infer<typeof stockActionSchema>;
