import { z } from 'zod';
import { categories } from '../shared/types';
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/), str=z.string().max(10000), count=z.number().int().min(0).max(10000), quantity=z.number().int().min(1).max(32);
const slot=z.object({id,bus:z.enum(['PCI','PCIe']),physical:z.number().int().min(1).max(16),lanes:z.number().int().min(1).max(16),generation:z.number().int().min(1).max(7),position:z.number().int().min(1).max(32)}).strict();
const specs=z.object({
 socket:str.optional(),formFactor:str.optional(),supportedForms:z.array(str).max(20).optional(),memoryType:str.optional(),dimmSlots:count.optional(),maxMemoryGb:count.optional(),capacityGb:z.number().min(0).max(10000000).optional(),
 slots:z.array(slot).max(32).refine(s=>new Set(s.map(x=>x.id)).size===s.length,'Slot IDs must be unique').refine(s=>new Set(s.map(x=>x.position)).size===s.length,'Slot positions must be unique').optional(),slotBus:z.enum(['PCI','PCIe']).optional(),slotWidth:z.number().int().min(1).max(16).optional(),requiredLanes:z.number().int().min(1).max(16).optional(),minGeneration:z.number().int().min(1).max(7).optional(),bracketWidth:z.number().int().min(1).max(8).optional(),
 lengthMm:count.optional(),heightMm:count.optional(),widthMm:count.optional(),maxCardLengthMm:count.optional(),maxCardHeightMm:count.optional(),maxCoolerHeightMm:count.optional(),rearSlots:count.optional(),bays25:count.optional(),bays35:count.optional(),hotSwapBays:count.optional(),sataPorts:count.optional(),m2Slots:count.optional(),m2Lengths:z.array(count).max(20).optional(),sataPower:count.optional(),
 usbA:count.optional(),usbC:count.optional(),ethernet:count.optional(),powerW:count.optional(),capacityW:count.optional(),driveInterface:z.enum(['SATA','NVMe']).optional(),driveSize:z.enum(['2.5','3.5','M.2']).optional(),m2Length:count.optional(),sledDrives:count.optional(),requiresBifurcation:z.boolean().optional(),bifurcation:z.boolean().optional(),sledHotSwap:z.boolean().optional(),supportsSockets:z.array(str).max(20).optional(),notes:str.optional()
}).strict();
export const schemas={
 components:z.object({id,name:z.string().min(1).max(200),category:z.enum(categories),manufacturer:str,specs,source:str,verified:z.boolean()}).strict(),
 systems:z.object({id,name:z.string().min(1).max(200),location:str,description:str,connections:z.array(z.object({id,name:z.string().min(1).max(200),usbA:count,usbC:count,ethernet:count,notes:str}).strict()).max(200)}).strict(),
 configurations:z.object({id,name:z.string().min(1).max(200),description:str,systemId:z.union([id,z.literal('')]),status:z.enum(['Draft','In review','Approved']),updatedAt:z.iso.datetime(),placements:z.array(z.object({id,componentId:id,quantity,slotId:str,role:z.enum(['boot','data','general']),mount:z.enum(['auto','internal','front-hot-swap','rear-sled']),group:str}).strict()).max(200).refine(p=>new Set(p.map(x=>x.id)).size===p.length,'Placement IDs must be unique'),storage:z.object({raid:z.enum(['none','mirror','raid5','raid6','raid10']),bootMirror:z.boolean()}).strict(),notes:str}).strict(),
 pcs:z.object({id,name:z.string().min(1).max(200),serial:str,location:str,configurationId:z.union([id,z.literal('')]),notes:str,buildSettings:z.object({systemId:z.union([id,z.literal('')]),storage:z.object({raid:z.enum(['none','mirror','raid5','raid6','raid10']),bootMirror:z.boolean()}).strict(),notes:str}).strict().nullable().default(null)}).strict(),
 inventory:z.object({id,componentId:id,tracking:z.enum(['serialized','bulk']),serial:str,assetTag:str,quantity:z.number().int().min(0).max(1000000),location:str,condition:z.enum(['Serviceable','Quarantined','Retired']),notes:str,
  allocations:z.array(z.object({id,pcId:id,quantity,state:z.enum(['reserved','installed']),plannedPlacementId:str,slotId:str,role:z.enum(['boot','data','general']),mount:z.enum(['auto','internal','front-hot-swap','rear-sled']),notes:str,createdAt:z.iso.datetime(),updatedAt:z.iso.datetime()}).strict()).max(10000),
  history:z.array(z.object({id,at:z.iso.datetime(),action:z.enum(['receive','adjust','edit','reserve','install','release','remove','configure','transfer-in','transfer-out']),quantity:z.number().int().min(-1000000).max(1000000),pcId:str,pcName:str,allocationId:str,notes:str}).strict()).max(100000).refine(events=>new Set(events.map(e=>e.id)).size===events.length,'Duplicate movement IDs')
 }).strict().superRefine((stock,ctx)=>{if(stock.tracking==='serialized'&&(stock.quantity!==1||!stock.serial.trim()))ctx.addIssue({code:'custom',message:'Serialized stock needs a serial number and quantity 1'});if(stock.tracking==='bulk'&&stock.serial.trim())ctx.addIssue({code:'custom',message:'Bulk lots cannot have a unit serial number'});if(stock.allocations.reduce((n,a)=>n+a.quantity,0)>stock.quantity)ctx.addIssue({code:'custom',message:'Allocations exceed stock quantity'});if(new Set(stock.allocations.map(a=>a.id)).size!==stock.allocations.length)ctx.addIssue({code:'custom',message:'Duplicate allocation IDs'});if(stock.condition==='Retired'&&stock.allocations.length)ctx.addIssue({code:'custom',message:'Release reservations and remove installations before retiring stock'});})
};
export type Collection=keyof typeof schemas;
export const stockActionSchema=z.discriminatedUnion('action',[
 z.object({action:z.enum(['reserve','install']),pcId:id,quantity,plannedPlacementId:str.default(''),slotId:str.optional(),role:z.enum(['boot','data','general']).optional(),mount:z.enum(['auto','internal','front-hot-swap','rear-sled']).optional(),notes:str.default('')}).strict(),
 z.object({action:z.enum(['install-reserved','release','remove']),allocationId:id,quantity,notes:str.default('')}).strict(),
 z.object({action:z.literal('configure'),allocationId:id,slotId:str,role:z.enum(['boot','data','general']),mount:z.enum(['auto','internal','front-hot-swap','rear-sled']),notes:str.default('')}).strict()
]);
export type StockAction=z.infer<typeof stockActionSchema>;
