<script setup lang="ts">
import {computed,ref,watch,nextTick,onMounted,onBeforeUnmount} from 'vue';
import {mdiClose} from '@mdi/js';
import type {Database} from '../shared/types';
import {locationKindChoices,isPCInstallationKind} from '../shared/types';
import {locationPath,installationLocationIds} from '../shared/installations';
import type {BulkRequest,BulkPreview,LocationPatch,PCPatch} from '../shared/bulk-records';
const props=defineProps<{request:BulkRequest|null;db:Database}>();
const emit=defineEmits<{close:[];reload:[];notify:[message:string];complete:[]}>();
const draft=ref<BulkRequest|null>(null),preview=ref<BulkPreview|null>(null),busy=ref(false),error=ref('');
let original='',opener:HTMLElement|undefined;
watch(()=>props.request,request=>{if(request){opener=document.activeElement instanceof HTMLElement?document.activeElement:undefined;draft.value=JSON.parse(JSON.stringify(request));original=JSON.stringify(draft.value);}else {draft.value=null;nextTick(()=>{if(opener?.isConnected)opener.focus();else document.getElementById('main-content')?.focus();});}preview.value=null;error.value='';},{immediate:true});
watch(draft,()=>{preview.value=null;},{deep:true});
const dirty=computed(()=>!!draft.value&&JSON.stringify(draft.value)!==original);
function hasUnsavedChanges(){return dirty.value;}
function confirmDiscard(){if(dirty.value&&!window.confirm('Discard pending bulk edits?'))return false;draft.value=null;emit('close');return true;}
defineExpose({hasUnsavedChanges,confirmDiscard});
function beforeUnload(e:BeforeUnloadEvent){if(dirty.value){e.preventDefault();e.returnValue='';}}
onMounted(()=>{window.addEventListener('beforeunload',beforeUnload);});onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload));
const locationPatch=computed(()=>draft.value?.collection==='installationLocations'&&draft.value.action==='edit'?draft.value.patch:{} as LocationPatch);
const pcPatch=computed(()=>draft.value?.collection==='pcs'&&draft.value.action==='edit'?draft.value.patch:{} as PCPatch);
const notes=computed(()=>draft.value?.action==='edit'?draft.value.patch.notes:undefined);
const parentChoices=computed(()=>{const excluded=new Set<string>();if(draft.value?.collection==='installationLocations')for(const id of draft.value.ids)for(const child of installationLocationIds(id,props.db))excluded.add(child);return [{title:'Top level (clear parent)',value:''},...props.db.installationLocations.filter(l=>!excluded.has(l.id)).map(l=>({title:locationPath(l.id,props.db),value:l.id}))];});
const assignmentChoices=computed(()=>[{title:'Unassigned (clear location)',value:''},...props.db.installationLocations.filter(l=>isPCInstallationKind(l.kind)).map(l=>({title:locationPath(l.id,props.db),value:l.id}))]);
const requirementChoices=computed(()=>[{title:'Clear requirements binding',value:''},...props.db.requirementsSets.filter(s=>s.versions.length).map(s=>({title:s.name,value:s.id}))]);
const requirementVersions=computed(()=>props.db.requirementsSets.find(s=>s.id===locationPatch.value.requirements?.setId)?.versions.map(v=>({title:`Revision ${v.revision} · ${v.name}`,value:v.revision}))||[]);
function chooseSet(){if(locationPatch.value.requirements)locationPatch.value.requirements.revision=props.db.requirementsSets.find(s=>s.id===locationPatch.value.requirements!.setId)?.versions.at(-1)?.revision||0;}
function toggleField(key:keyof LocationPatch|keyof PCPatch,enabled:boolean){if(draft.value?.action!=='edit')return;const patch=draft.value.patch as Record<string,unknown>;if(!enabled){delete patch[key];return;}const defaults:Record<string,unknown>={kind:'Area',parentId:'',targetConfigurationId:'',requirements:{setId:'',revision:0},installationLocationId:'',lifecycle:'Maintenance',notes:{mode:'append',value:''}};patch[key]=defaults[key];}
const canPreview=computed(()=>draft.value&&draft.value.ids.length<=500&&(draft.value.action==='delete'||Object.keys(draft.value.patch).length>0));
const headers=[{title:'Record',key:'name'},{title:'Before',key:'before',sortable:false},{title:'After',key:'after',sortable:false}];
async function createPreview(event?:PromiseLike<{valid:boolean}>){if(!await validateForm('draft',event)||!canPreview.value||busy.value)return;if(!draft.value)return;busy.value=true;error.value='';preview.value=null;const request=JSON.parse(JSON.stringify(draft.value)),fingerprint=JSON.stringify(request);try{const r=await fetch('/api/bulk/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)}),data=await r.json();if(!r.ok)throw Error(data.error||'Preview failed');if(JSON.stringify(draft.value)!==fingerprint)throw Error('The edits changed during preview. Preview again.');preview.value=data;}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
async function apply(){if(busy.value||!await validateForm('draft')||busy.value)return;if(!draft.value||!preview.value?.valid)return;const reviewed=preview.value,request=JSON.parse(JSON.stringify(draft.value));busy.value=true;error.value='';try{const r=await fetch('/api/bulk/apply',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':reviewed.revision},body:JSON.stringify({request,token:reviewed.token})}),body=await r.json();if(!r.ok)throw Error(body.error||'Bulk action failed');draft.value=null;emit('reload');emit('complete');emit('notify',`${body.updated} ${request.collection==='pcs'?'PC':'location'} records ${request.action==='delete'?'deleted':'updated'}.`);emit('close');}catch(e){preview.value=null;error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
type EditorForm={validate:()=>Promise<{valid:boolean}>;$el?:HTMLElement};
const forms:Record<string,EditorForm|null>={};
function setForm(name:string,form:unknown){forms[name]=form as EditorForm|null;}
const requiredValue=(v:unknown)=>v!==null&&v!==undefined&&String(v).trim()!==''||'A value is required.';
const nonnegativeValue=(v:unknown)=>v===null||v===undefined||v===''||Number.isFinite(Number(v))&&Number(v)>=0||'Enter a non-negative number.';
async function validateForm(name:string,event?:PromiseLike<{valid:boolean}>){const form=forms[name];if(!form)return false;const {valid}=event?await event:await form.validate();if(!valid){await nextTick();form.$el?.querySelector<HTMLElement>('.v-input--error input, .v-input--error textarea, .v-input--error button')?.focus();}return valid;}
</script>
<template>
<v-dialog scrollable :model-value="!!draft" max-width="1100" persistent aria-labelledby="bulk-record-title" @keydown.esc.stop.prevent="!busy&&confirmDiscard()"><v-form :ref="form=>setForm('draft',form)" @submit.prevent="createPreview"><v-card v-if="draft" class="editor-dialog bulk-record-editor"><v-card-title class="dialog-head" style="white-space:normal"><h2 id="bulk-record-title">{{draft.action==='delete'?'Delete':'Edit'}} {{draft.ids.length}} selected {{draft.collection==='pcs'?'PCs':'locations'}}</h2><v-btn :icon="mdiClose" variant="text" aria-label="Close bulk action" :disabled="busy" @click="confirmDiscard" /></v-card-title><v-card-text class="dialog-body"><v-alert v-if="error" type="error" role="alert">{{error}}</v-alert><p>Only the selected record IDs are included, including selected rows hidden by the current filter. Changes are applied together after preview; no partial changes are saved.</p>
<template v-if="draft.action==='edit'"><p>Enable each field you want to change. Disabled fields retain their existing values.</p><div v-if="draft.collection==='installationLocations'" class="form-grid"><div><v-checkbox :model-value="locationPatch.kind!==undefined" label="Change location type" :disabled="busy" @update:model-value="v=>toggleField('kind',!!v)" hide-details /><v-select v-if="locationPatch.kind!==undefined" v-model="locationPatch.kind" label="New location type" :items="locationKindChoices" :disabled="busy" /></div><div><v-checkbox :model-value="locationPatch.parentId!==undefined" label="Change parent location" :disabled="busy" @update:model-value="v=>toggleField('parentId',!!v)" hide-details /><v-autocomplete v-if="locationPatch.parentId!==undefined" v-model="locationPatch.parentId" label="New parent location" :items="parentChoices" :disabled="busy" /></div><div><v-checkbox :model-value="locationPatch.targetConfigurationId!==undefined" label="Change target configuration" :disabled="busy" @update:model-value="v=>toggleField('targetConfigurationId',!!v)" hide-details /><v-autocomplete v-if="locationPatch.targetConfigurationId!==undefined" v-model="locationPatch.targetConfigurationId" label="New target configuration" :items="[{title:'Clear target',value:''},...db.configurations.map(c=>({title:c.name,value:c.id}))]" :disabled="busy" /></div><div><v-checkbox :model-value="!!locationPatch.requirements" label="Change pinned requirements" :disabled="busy" @update:model-value="v=>toggleField('requirements',!!v)" hide-details /><template v-if="locationPatch.requirements"><v-autocomplete v-model="locationPatch.requirements.setId" label="New requirements set" :items="requirementChoices" :disabled="busy" @update:model-value="chooseSet" /><v-select v-if="locationPatch.requirements.setId" v-model="locationPatch.requirements.revision" label="New requirements revision" :items="requirementVersions" :disabled="busy" /></template></div></div>
<div v-else class="form-grid"><div><v-checkbox :model-value="pcPatch.installationLocationId!==undefined" label="Change PC installation assignment" :disabled="busy" @update:model-value="v=>toggleField('installationLocationId',!!v)" hide-details /><v-autocomplete v-if="pcPatch.installationLocationId!==undefined" v-model="pcPatch.installationLocationId" label="New PC installation" :items="assignmentChoices" :disabled="busy" /></div><div><v-checkbox :model-value="pcPatch.lifecycle!==undefined" label="Change PC lifecycle" :disabled="busy" @update:model-value="v=>toggleField('lifecycle',!!v)" hide-details /><v-select v-if="pcPatch.lifecycle!==undefined" v-model="pcPatch.lifecycle" label="New PC lifecycle" :items="['Planning','Building','Maintenance','Parts only','Retired']" :disabled="busy" /></div><p class="form-hint">Commissioning and return to service require individual lifecycle checks. Retirement still requires removing all parts and reservations.</p></div>
<v-checkbox :model-value="!!notes" label="Change notes" :disabled="busy" @update:model-value="v=>toggleField('notes',!!v)" hide-details /><div v-if="notes" class="form-grid"><v-select v-model="notes.mode" label="Notes action" :items="[{title:'Append to each record',value:'append'},{title:'Replace (empty clears notes)',value:'replace'}]" :disabled="busy" /><v-textarea v-model="notes.value" label="Common notes" rows="2" :disabled="busy" /></div></template>
<p v-else-if="draft.collection==='installationLocations'">Deletion removes only explicitly selected locations. Unselected children and assigned PCs block deletion; move or unassign PCs first. Historical commissioning snapshots keep their captured location context.</p><p v-else>Deletion removes PC records and their timelines and commissioning snapshots. Current reservations or installed parts block deletion. Inventory movement history remains preserved. Export a backup if you need to retain deleted PC history.</p>
<v-btn variant="outlined" :disabled="busy||!canPreview" :loading="busy" type="submit">Preview selected changes</v-btn><section v-if="preview" class="mt-5"><v-alert v-if="!preview.valid" type="error" role="alert" title="Bulk action blocked">{{preview.error}}</v-alert><template v-else><h3>Review {{preview.rows.length}} records</h3><p role="status">{{preview.affectedPCs}} PCs in scope · {{preview.pathChanges}} descendant location paths also change<span v-if="preview.historicalPCs"> · {{preview.historicalPCs}} PC records have historical data that will be deleted</span></p><v-data-table v-table-scroll :headers="headers" :items="preview.rows" item-value="id" :items-per-page="10" :items-per-page-options="[10,25,50]" :mobile="false"><template #caption><caption class="sr-only">Selected bulk changes before and after</caption></template></v-data-table></template></section></v-card-text><v-card-actions class="dialog-footer"><v-btn variant="text" :disabled="busy" @click="confirmDiscard">Cancel</v-btn><v-btn variant="flat" :color="draft.action==='delete'?'error':'primary'" :disabled="busy||!preview?.valid" @click="apply">{{draft.action==='delete'?'Delete':'Apply changes to'}} {{draft.ids.length}} {{draft.collection==='pcs'?'PCs':'locations'}}</v-btn></v-card-actions></v-card></v-form></v-dialog>
</template>
