<script setup lang="ts">
import {computed,ref,watch,onMounted,onBeforeUnmount,onUpdated} from 'vue';
import type {Component,Database} from '../shared/types';
import {categories} from '../shared/types';
import {catalogFields,missingFields,fieldValue,isMissing,type EnrichmentJob} from '../shared/catalog-quality';
import {catalogSuggestions,normalizeCatalogValue,normalizeCatalogValues} from '../shared/catalog-options';
import {pcPartPickerURL} from '../shared/product-enrichment';
const props=defineProps<{db:Database;revision:string}>();
const emit=defineEmits<{reload:[];notify:[message:string];editComponent:[component:Component]}>();
const tab=ref('gaps'),search=ref(''),category=ref(''),onlyMissing=ref(true),onlyUsed=ref(false),selected=ref<string[]>([]),field=ref(''),value=ref<unknown>(''),busy=ref(false),error=ref(''),jobs=ref<EnrichmentJob[]>([]),running=ref(false),urls=ref<Record<string,string>>({}),reviewKeys=ref<Record<string,string[]>>({}),files=ref<Record<string,File|undefined>>({});
const used=computed(()=>new Set([...props.db.inventory.map(s=>s.componentId),...props.db.configurations.flatMap(c=>c.placements.map(p=>p.componentId))]));
const rows=computed(()=>props.db.components.map(c=>({component:c,missing:missingFields(c)})).filter(r=>(!category.value||r.component.category===category.value)&&(!onlyMissing.value||r.missing.length>0||!r.component.verified)&&(!onlyUsed.value||used.value.has(r.component.id))&&`${r.component.name} ${r.component.manufacturer} ${r.component.category}`.toLowerCase().includes(search.value.toLowerCase())));
watch(()=>props.db.components,components=>{const ids=new Set(components.map(c=>c.id));selected.value=selected.value.filter(id=>ids.has(id));});
const selection=computed(()=>props.db.components.filter(c=>selected.value.includes(c.id)));
const commonFields=computed(()=>{const first=selection.value[0];return first?catalogFields(first).filter(f=>selection.value.every(c=>catalogFields(c).some(other=>other.key===f.key))&&selection.value.some(c=>isMissing(fieldValue(c,f.key)))):[];});
const selectedField=computed(()=>commonFields.value.find(f=>f.key===field.value));
const fillCount=computed(()=>selection.value.filter(c=>isMissing(fieldValue(c,field.value))).length);
const suggestions=computed(()=>selectedField.value?.choices||catalogSuggestions(props.db,field.value));
watch(field,()=>{value.value=selectedField.value?.kind==='array'?[]:selectedField.value?.kind==='boolean'?false:'';});
watch(commonFields,fields=>{if(!fields.some(f=>f.key===field.value))field.value='';});
function toggle(id:string,checked:boolean){selected.value=checked?[...new Set([...selected.value,id])]:selected.value.filter(x=>x!==id);}
function selectVisible(){selected.value=rows.value.slice(0,100).map(r=>r.component.id);}
function hasUnsavedChanges(){return !!field.value&&!isMissing(value.value)||Object.keys(urls.value).length>0||Object.values(files.value).some(Boolean);}
function confirmDiscard(){if(hasUnsavedChanges()&&!window.confirm('Discard pending catalog fill values and queue URLs?'))return false;field.value='';urls.value={};files.value={};return true;}
defineExpose({hasUnsavedChanges,confirmDiscard});
function beforeUnload(event:BeforeUnloadEvent){if(hasUnsavedChanges()){event.preventDefault();event.returnValue='';}}
async function request(url:string,body:unknown){const response=await fetch(url,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':props.revision},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
async function perform(action:()=>Promise<void>){busy.value=true;error.value='';try{await action();}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
async function poll(){try{const r=await fetch('/api/enrichment');if(!r.ok)return;const data=await r.json();jobs.value=data.jobs;running.value=data.running;for(const j of jobs.value){if(j.state!=='review'||!j.proposal){delete reviewKeys.value[j.id];continue;}const keys=Object.keys(j.proposal.patch);reviewKeys.value[j.id]=reviewKeys.value[j.id]?reviewKeys.value[j.id].filter(key=>keys.includes(key)):keys;}}catch{/* Explicit queue actions report connection failures. */}}
function labelTables(){for(const wrapper of document.querySelectorAll<HTMLElement>('.catalog-maintenance .v-table__wrapper')){wrapper.tabIndex=0;wrapper.setAttribute('role','region');wrapper.setAttribute('aria-label',`${wrapper.querySelector('caption')?.textContent?.trim()||'Catalog data'}; scroll to view all columns`);}}
onUpdated(labelTables);
let timer:ReturnType<typeof setInterval>;onMounted(()=>{labelTables();void poll();timer=setInterval(()=>void poll(),2500);window.addEventListener('beforeunload',beforeUnload);});onBeforeUnmount(()=>{clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload);});
function currentValue(job:EnrichmentJob,key:string){const c=props.db.components.find(c=>c.id===job.componentId);if(!c)return 'Component removed';const value=fieldValue(c,key);return isMissing(value)?'Missing':value;}
function urlFor(c:Component){return urls.value[c.id]??c.source;}
function queueable(c:Component){try{return pcPartPickerURL(urlFor(c));}catch{return '';}}
async function fill(){await perform(async()=>{let normalized=value.value;if(selectedField.value?.kind==='number')normalized=Number(value.value);if(selectedField.value?.kind==='text')normalized=normalizeCatalogValue(value.value,suggestions.value);if(selectedField.value?.kind==='array')normalized=normalizeCatalogValues(value.value,suggestions.value);await request('/api/catalog/bulk-fill',{componentIds:selected.value,patch:{[field.value]:normalized}});field.value='';value.value='';emit('reload');emit('notify','Missing values filled; existing values preserved. Updated components need verification.');});}
async function enqueue(){await perform(async()=>{const valid=selection.value.filter(c=>queueable(c));if(!valid.length)throw Error('Enter a PCPartPicker product URL for at least one selected component.');const result=await request('/api/enrichment/enqueue',{items:valid.map(c=>({componentId:c.id,url:queueable(c)}))});for(const c of valid)delete urls.value[c.id];await poll();tab.value='queue';emit('notify',`${result.added.length} items queued; ${selection.value.length-valid.length} skipped without a supported URL. Existing active jobs are not duplicated.`);});}
async function control(action:'start'|'pause'|'clear'){await perform(async()=>{await request('/api/enrichment/control',{action});await poll();});}
async function jobAction(job:EnrichmentJob,action:'retry'|'cancel'|'apply'|'upload'){await perform(async()=>{const body:Record<string,unknown>={action};if(action==='apply'){body.keys=reviewKeys.value[job.id]||[];body.proposalId=job.proposalId;}if(action==='upload'){const file=files.value[job.id];if(!file)throw Error('Select a saved product HTML file.');if(file.size>2*1024*1024)throw Error('Saved HTML must be at most 2 MiB.');body.html=await file.text();}await request(`/api/enrichment/${job.id}/action`,body);if(action==='apply')emit('reload');if(action==='upload')delete files.value[job.id];await poll();});}
</script>
<template>
<div class="catalog-maintenance"><div class="page-heading"><div><h1>Catalog data</h1><p>Find category-specific engineering gaps, fill common missing values, and review fetched product details.</p></div><v-btn variant="outlined" href="/api/export/components">Export component CSV</v-btn></div><v-alert v-if="error" type="error" role="alert" class="mb-5">{{error}}<v-btn variant="text" @click="emit('reload')">Reload current workspace</v-btn></v-alert><v-tabs v-model="tab" aria-label="Catalog maintenance views" color="primary" class="content-tabs"><v-tab value="gaps">Missing data</v-tab><v-tab value="queue">Enrichment queue ({{jobs.filter(j=>['queued','fetching','review'].includes(j.state)).length}})</v-tab></v-tabs>
<template v-if="tab==='gaps'"><section class="panel build-notes"><div class="form-grid"><v-text-field v-model="search" label="Search catalog data" /><v-select v-model="category" label="Component category" :items="[{title:'All categories',value:''},...categories.map(value=>({title:value,value}))]" /><v-checkbox v-model="onlyMissing" label="Missing data or unverified only" hide-details /><v-checkbox v-model="onlyUsed" label="Only used in plans or inventory" hide-details /></div><p>Unknown values are gaps; explicit zero and false are known values. These checks cover category-specific core fields. Detailed slots, ports, bays, wiring and manufacturer verification still need engineering review.</p><div class="heading-actions"><v-btn variant="outlined" @click="selectVisible">Select up to 100 shown</v-btn><v-btn variant="text" @click="selected=[]">Clear selection</v-btn><span role="status">{{rows.length}} shown · {{selection.length}} selected (including hidden rows)</span></div>
<v-table><caption class="sr-only">Missing catalog fields and verification status</caption><thead><tr><th scope="col">Select</th><th scope="col">Component</th><th scope="col">Missing fields</th><th scope="col">Verification</th><th scope="col">PCPartPicker URL</th><th scope="col">Action</th></tr></thead><tbody><tr v-for="row in rows" :key="row.component.id"><td><v-checkbox :model-value="selected.includes(row.component.id)" :aria-label="`Select ${row.component.name}`" hide-details @update:model-value="v=>toggle(row.component.id,!!v)" /></td><td><strong>{{row.component.name}}</strong><small>{{row.component.category}}</small></td><td>{{row.missing.map(f=>f.label).join(', ')||'No core field gaps'}}</td><td>{{row.component.verified?'Verified':'Needs verification'}}</td><td><v-text-field :model-value="urlFor(row.component)" :aria-label="`PCPartPicker URL for ${row.component.name}`" placeholder="https://pcpartpicker.com/product/…" @update:model-value="v=>urls[row.component.id]=String(v||'')" /></td><td><v-btn variant="text" @click="emit('editComponent',row.component)">Edit part<span class="sr-only"> {{row.component.name}}</span></v-btn></td></tr></tbody></v-table><p v-if="!rows.length">No matching catalog records.</p></section>
<section class="panel build-notes"><h2>Bulk fill missing values</h2><p>Select components above. Only shared applicable fields can be filled; populated values are preserved. Any changed component becomes unverified.</p><div class="form-grid"><v-select v-model="field" label="Field to fill" :items="commonFields.map(f=>({title:f.label,value:f.key}))" :disabled="!selection.length" /><v-text-field v-if="selectedField?.kind==='number'" v-model="value" :label="selectedField.label" type="number" min="0" /><v-checkbox v-else-if="selectedField?.kind==='boolean'" v-model="value" :label="selectedField.label" /><v-combobox v-else-if="selectedField?.kind==='array'" v-model="value" :label="selectedField.label" :items="suggestions" multiple chips closable-chips /><v-combobox v-else-if="selectedField" v-model="value" :label="selectedField.label" :items="suggestions" /></div><p v-if="selectedField" role="status">{{fillCount}} missing values will be filled; {{selection.length-fillCount}} populated values will be preserved.</p><v-btn color="primary" :loading="busy" :disabled="!selectedField||isMissing(value)||selection.length>100" @click="fill">Fill {{fillCount}} missing values</v-btn></section>
<section class="panel build-notes"><h2>Queue product enrichment</h2><p>Enter exact product URLs above, then queue selected components. URL overrides belong to the queue and do not replace catalog source documentation. Live requests run one at a time, with a delay and a timeout. Fetching is paused after restart.</p><v-btn color="primary" :loading="busy" :disabled="!selection.length||selection.length>100" @click="enqueue">Queue selected parts</v-btn></section></template>
<template v-else><section class="panel build-notes"><h2>PCPartPicker enrichment queue</h2><p>Fetched specifications are proposals. Confirm each source product matches your part, select fields, then apply. Only still-missing fields are filled; cards and custom engineering details may need manual entry. Blocked pages can be uploaded as saved HTML.</p><div class="heading-actions"><v-btn color="primary" :disabled="running||busy||!jobs.some(j=>j.state==='queued')" @click="control('start')">Start fetch queue</v-btn><v-btn variant="outlined" :disabled="!running||busy" @click="control('pause')">Pause fetch queue</v-btn><v-btn variant="text" :disabled="running||busy" @click="control('clear')">Clear completed / failed history</v-btn><span role="status">{{running?'Fetching':'Paused / idle'}}</span></div></section>
<section v-for="job in [...jobs].reverse()" :key="job.id" class="panel build-notes"><div class="section-head"><h3>{{job.name}}</h3><strong>{{job.state}}</strong></div><p><a :href="job.url" target="_blank" rel="noopener noreferrer">{{job.url}}</a></p><p>{{job.message}}</p><template v-if="job.state==='review'&&job.proposal"><v-table><caption class="sr-only">Proposed missing data for {{job.name}}</caption><thead><tr><th scope="col">Apply</th><th scope="col">Field</th><th scope="col">Current value</th><th scope="col">Proposed value</th><th scope="col">Source evidence</th></tr></thead><tbody><tr v-for="(candidate,key) in job.proposal.patch" :key="key"><td><v-checkbox v-model="reviewKeys[job.id]" :value="String(key)" :aria-label="`Apply ${String(key)} for ${job.name}`" hide-details /></td><td>{{key}}</td><td>{{currentValue(job,String(key))}}</td><td>{{Array.isArray(candidate)?candidate.join(', '):candidate}}</td><td>{{job.proposal.evidence[key]}}</td></tr></tbody></v-table><v-btn color="primary" :disabled="busy||!db.components.some(c=>c.id===job.componentId)||!reviewKeys[job.id]?.length" @click="jobAction(job,'apply')">Confirm product and apply selected fields</v-btn></template><div v-if="['queued','failed','review'].includes(job.state)" class="form-grid mt-4"><v-file-input v-model="files[job.id]" label="Saved product HTML (2 MiB maximum)" accept=".html,.htm,text/html" /><v-btn variant="outlined" :disabled="busy||!files[job.id]" @click="jobAction(job,'upload')">Read saved HTML</v-btn></div><v-btn v-if="job.state==='failed'" variant="outlined" :disabled="busy" @click="jobAction(job,'retry')">Retry fetch</v-btn><v-btn v-if="['queued','fetching','review','failed'].includes(job.state)" variant="text" :disabled="busy" @click="jobAction(job,'cancel')">Cancel item</v-btn></section><p v-if="!jobs.length">No queued parts. Select components with product URLs in Missing data.</p></template>
</div>
</template>
