<script setup lang="ts">
import { computed } from 'vue';
import type { Component, Configuration, Database, System, Placement, PortKind } from '../shared/types';
import SoftwareEditor from './SoftwareEditor.vue';
const props=defineProps<{component?:Component;configuration?:Configuration;system?:System;db:Database;settingsOnly?:boolean}>();
const uid=()=>crypto.randomUUID();
const kinds:PortKind[]=['USB-A','USB-C','Ethernet'];
const raids=['none','mirror','raid5','raid6','raid10'];
const mounts:Placement['mount'][]=['auto','internal','front-hot-swap','rear-sled'];
const list=(s:unknown)=>String(s||'').split(',').map(v=>v.trim()).filter(Boolean);
const part=(id:string)=>props.db.components.find(c=>c.id===id);
const selectedParts=computed(()=>props.configuration?.placements.map(p=>part(p.componentId)).filter((p):p is Component=>!!p)||[]);
const providerItems=computed(()=>[{title:'Unbound',value:''},...(props.configuration?.placements.filter(p=>['Chassis','Motherboard','Storage adapter'].includes(part(p.componentId)?.category||'')).map(p=>({title:part(p.componentId)?.name||p.id,value:p.id}))||[])]);
const controllerItems=computed(()=>[{title:'Unspecified',value:''},...(props.configuration?.placements.filter(p=>['Motherboard','Storage adapter'].includes(part(p.componentId)?.category||'')).map(p=>({title:part(p.componentId)?.name||p.id,value:p.id}))||[])]);
function targets(p:Placement){const provider=props.configuration?.placements.find(x=>x.id===p.adapterPlacementId);return [{title:'Unbound',value:''},...(provider?part(provider.componentId)?.specs.driveTargets||[]:[]).map(t=>({title:t.id,value:t.id}))];}
function setOptional(object:object,key:string,value:unknown,numeric=false){const row=object as Record<string,unknown>;if(value===null||value===undefined||value==='')delete row[key];else row[key]=numeric?Number(value):value;}
function nextId(prefix:string,rows:{id:string}[]=[]){let n=1;while(rows.some(r=>r.id===`${prefix}_${n}`))n++;return `${prefix}_${n}`;}
function bindTarget(p:Placement,value:string){p.targetId=value;const provider=props.configuration?.placements.find(x=>x.id===p.adapterPlacementId);const target=provider&&part(provider.componentId)?.specs.driveTargets?.find(t=>t.id===value);if(target&&p.mount==='auto')p.mount=target.mount;}
function addPort(){if(props.component)(props.component.specs.ports??=[]).push({id:nextId('PORT',props.component.specs.ports),kind:'Ethernet'});}
function addTarget(){if(props.component)(props.component.specs.driveTargets??=[]).push({id:nextId('BAY',props.component.specs.driveTargets),mount:props.component.category==='Storage adapter'?'rear-sled':'internal'});}
function addRule(){if(props.component)(props.component.specs.laneRules??=[]).push({id:nextId('RULE',props.component.specs.laneRules),slots:[]});}
function addGroup(){if(props.configuration)(props.configuration.storage.groups??=[]).push({id:uid(),name:'New array',raid:'mirror'});}
function portOptions(){return props.configuration?.placements.flatMap(p=>Array.from({length:p.quantity},(_,instance)=>(part(p.componentId)?.specs.ports||[]).map(port=>({title:`${part(p.componentId)?.name} #${instance+1} / ${port.id}`,value:`${p.id}|${instance}|${port.id}`}))).flat())||[];}
function choosePort(mapping:{placementId:string;instance:number;portId:string},value:string){const [placementId,instance,portId]=value.split('|');Object.assign(mapping,{placementId,instance:Number(instance),portId});}
function mappings(){const system=props.db.systems.find(s=>s.id===props.configuration?.systemId);return system?.connections.flatMap(c=>(c.requirements||[]).map(r=>({title:`${c.name}: ${r.id} (${r.kind})`,value:`${c.id}|${r.id}`})))||[];}
function addMapping(){if(props.configuration)(props.configuration.portMappings??=[]).push({connectionId:'',requirementId:'',placementId:'',instance:0,portId:''});}
</script>
<template>
 <section v-if="component" class="mt-6">
  <h3>Detailed interfaces & topology</h3><p class="form-hint">Structured ports and drive targets provide physical mappings. Leave undocumented capabilities blank.</p>
  <div class="form-grid"><v-text-field :model-value="component.specs.supportedOS?.join(', ')" label="Supported operating systems (comma separated)" @update:model-value="v=>component!.specs.supportedOS=list(v)" /><v-text-field v-model="component.specs.requiredDriver" label="Required driver identifier / version" /><v-text-field v-model="component.specs.requiredFirmware" label="Required firmware identifier / version" /><v-text-field v-model="component.specs.bifurcationMode" label="Required bifurcation mode (e.g. x4/x4/x4/x4)" /><v-select :model-value="component.specs.pciVoltage" @update:model-value="v=>setOptional(component!.specs,'pciVoltage',v)" label="Conventional PCI keying / voltage" :items="['3.3V','5V','universal']" clearable /><v-select :model-value="component.specs.pciBits" @update:model-value="v=>setOptional(component!.specs,'pciBits',v)" label="PCI connector bits" :items="[32,64]" clearable /><v-select :model-value="component.specs.bootable" @update:model-value="v=>setOptional(component!.specs,'bootable',v)" label="Controller supports boot" :items="[{title:'Unknown',value:undefined},{title:'Yes',value:true},{title:'No',value:false}]" /><v-select :model-value="component.specs.hotPlug" @update:model-value="v=>setOptional(component!.specs,'hotPlug',v)" label="Controller supports hot-plug" :items="[{title:'Unknown',value:undefined},{title:'Yes',value:true},{title:'No',value:false}]" /></div>
  <div v-for="slot in component.specs.slots" :key="slot.id" class="panel pa-4 mb-3"><strong>{{slot.id}} capabilities</strong><div class="form-grid mt-3"><v-text-field :model-value="slot.bifurcationModes?.join(', ')" label="Supported bifurcation modes (comma separated)" @update:model-value="v=>slot.bifurcationModes=list(v)" /><v-select :model-value="slot.pciVoltage" @update:model-value="v=>setOptional(slot,'pciVoltage',v)" label="PCI voltage" :items="['3.3V','5V','universal']" clearable /><v-select :model-value="slot.pciBits" @update:model-value="v=>setOptional(slot,'pciBits',v)" label="PCI connector bits" :items="[32,64]" clearable /></div></div>
  <div class="spec-heading"><h3>Physical ports</h3><v-btn size="small" @click="addPort">Add port</v-btn></div>
  <div v-for="(port,i) in component.specs.ports" :key="i" class="panel pa-4 mb-3"><div class="form-grid"><v-text-field v-model="port.id" label="Port ID" required aria-required="true" /><v-select v-model="port.kind" label="Connector" :items="kinds" /><v-text-field v-model="port.protocol" label="Protocol (e.g. USB 3.2, TCP/IP)" /><v-text-field :model-value="port.speedMbps" @update:model-value="v=>setOptional(port,'speedMbps',v,true)" label="Speed (Mbps)" type="number" min="0" /><v-text-field :model-value="port.powerW" @update:model-value="v=>setOptional(port,'powerW',v,true)" label="Supplied power (W)" type="number" min="0" /><v-select :model-value="port.isolated" @update:model-value="v=>setOptional(port,'isolated',v)" label="Dedicated / isolated" :items="[{title:'Unknown',value:undefined},{title:'Yes',value:true},{title:'No',value:false}]" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove port ${port.id || i+1}`" @click="component.specs.ports?.splice(i,1)">Remove port</v-btn></div>
  <div class="spec-heading"><h3>Individual drive targets</h3><v-btn size="small" @click="addTarget">Add bay / sled position</v-btn></div>
  <div v-for="(target,i) in component.specs.driveTargets" :key="i" class="panel pa-4 mb-3"><div class="form-grid"><v-text-field v-model="target.id" label="Bay / target ID" required aria-required="true" /><v-select v-model="target.mount" label="Mount" :items="mounts" /><v-select v-model="target.driveSizes" multiple label="Supported drive sizes" :items="['2.5','3.5','M.2']" /><v-select v-model="target.interfaces" multiple label="Interfaces" :items="['SATA','NVMe']" /><v-text-field :model-value="target.m2Lengths?.join(', ')" label="M.2 lengths (mm, comma separated)" @update:model-value="v=>target.m2Lengths=list(v).map(Number)" /><v-select :model-value="target.hotSwap" @update:model-value="v=>setOptional(target,'hotSwap',v)" label="Backplane / target hot-swap" :items="[{title:'Unknown',value:undefined},{title:'Yes',value:true},{title:'No',value:false}]" /><v-select :model-value="target.bootable" @update:model-value="v=>setOptional(target,'bootable',v)" label="Boot supported" :items="[{title:'Unknown',value:undefined},{title:'Yes',value:true},{title:'No',value:false}]" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove drive target ${target.id || i+1}`" @click="component.specs.driveTargets?.splice(i,1)">Remove target</v-btn></div>
  <div class="spec-heading"><h3>Shared motherboard resources</h3><v-btn size="small" @click="addRule">Add resource rule</v-btn></div>
  <div v-for="(rule,i) in component.specs.laneRules" :key="i" class="panel pa-4 mb-3"><div class="form-grid"><v-text-field v-model="rule.id" label="Rule ID" required aria-required="true" /><v-select v-model="rule.slots" multiple label="Slots affected" :items="component.specs.slots?.map(s=>s.id)||[]" /><v-text-field :model-value="rule.maxLanes" @update:model-value="v=>setOptional(rule,'maxLanes',v,true)" label="Shared lane budget" type="number" min="0" /><v-switch v-model="rule.exclusive" label="Only one of these slots may be occupied" /><v-text-field :model-value="rule.disableM2Slots" @update:model-value="v=>setOptional(rule,'disableM2Slots',v,true)" label="M.2 slots disabled when occupied" type="number" min="0" /><v-text-field :model-value="rule.disableSataPorts" @update:model-value="v=>setOptional(rule,'disableSataPorts',v,true)" label="SATA ports disabled when occupied" type="number" min="0" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove resource rule ${rule.id || i+1}`" @click="component.specs.laneRules?.splice(i,1)">Remove rule</v-btn></div>
 </section>
 <section v-if="system" class="mt-6"><h3>Structured instrument requirements</h3><p class="form-hint">Map these requirements to individual PC ports in the configuration. Keep legacy counts consistent with the required connections.</p><div v-for="connection in system.connections" :key="connection.id" class="panel pa-4 mb-4"><div class="spec-heading"><strong>{{connection.name||'Unnamed equipment'}}</strong><v-btn size="small" @click="(connection.requirements??=[]).push({id:uid(),kind:'Ethernet',quantity:1})">Add requirement</v-btn></div><div v-for="(r,i) in connection.requirements" :key="r.id" class="mb-4"><div class="form-grid"><v-text-field v-model="r.id" label="Requirement ID" required aria-required="true" /><v-select v-model="r.kind" label="Connector" :items="kinds" /><v-text-field v-model.number="r.quantity" label="Quantity" type="number" min="1" /><v-text-field v-model="r.protocol" label="Protocol" /><v-text-field :model-value="r.minSpeedMbps" @update:model-value="v=>setOptional(r,'minSpeedMbps',v,true)" label="Minimum speed (Mbps)" type="number" min="0" /><v-text-field :model-value="r.minPowerW" @update:model-value="v=>setOptional(r,'minPowerW',v,true)" label="Minimum supplied power (W)" type="number" min="0" /><v-switch v-model="r.isolated" label="Requires dedicated isolation" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove requirement ${r.id || i+1} from ${connection.name || 'equipment'}`" @click="connection.requirements?.splice(i,1)">Remove requirement</v-btn></div></div></section>
 <section v-if="configuration" class="mt-4">
  <div class="spec-heading"><h3>Named data arrays</h3><v-btn size="small" @click="addGroup">Add array</v-btn></div><p class="form-hint">Ungrouped data drives use the default data redundancy. Named groups calculate independently.</p>
  <div v-for="(group,i) in configuration.storage.groups" :key="group.id" class="panel pa-4 mb-3"><div class="form-grid"><v-text-field v-model="group.name" label="Array name" required aria-required="true" /><v-select v-model="group.raid" label="Redundancy" :items="raids" /><v-select v-model="group.controllerPlacementId" label="Controller" :items="controllerItems" /><v-text-field v-model="group.notes" label="Array notes" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove array ${group.name || i+1}`" @click="configuration.storage.groups?.splice(i,1)">Remove array</v-btn></div>
  <template v-if="!settingsOnly"><h3 class="my-4">Drive bindings</h3><div v-for="p in configuration.placements.filter(p=>part(p.componentId)?.category==='Drive')" :key="p.id" class="panel pa-4 mb-3"><strong>{{part(p.componentId)?.name}} × {{p.quantity}}</strong><p v-if="p.quantity>1" class="form-hint">Split this line into individual drives to assign individual bays.</p><div class="form-grid mt-3"><v-select v-model="p.group" label="Data array" :items="[{title:'Default array',value:''},...(configuration.storage.groups||[]).map(g=>({title:g.name,value:g.id}))]" /><v-select v-model="p.adapterPlacementId" label="Bay / sled provider" :items="providerItems" @update:model-value="p.targetId=''" /><v-select :model-value="p.targetId" @update:model-value="v=>bindTarget(p,v)" label="Individual target" :items="targets(p)" /><v-select v-model="p.controllerPlacementId" label="Drive controller" :items="controllerItems" /></div></div>
  </template><div class="spec-heading"><h3>Instrument-to-port mapping</h3><v-btn size="small" @click="addMapping">Map connection</v-btn></div><div v-for="(mapping,i) in configuration.portMappings" :key="i" class="panel pa-4 mb-3"><div class="form-grid"><v-select :model-value="`${mapping.connectionId}|${mapping.requirementId}`" label="Equipment requirement" :items="mappings()" @update:model-value="v=>{const [c,r]=v.split('|');mapping.connectionId=c;mapping.requirementId=r;}" /><v-select :model-value="`${mapping.placementId}|${mapping.instance}|${mapping.portId}`" label="Physical PC port" :items="portOptions()" @update:model-value="v=>choosePort(mapping,v)" /></div><v-btn size="small" color="error" variant="text" :aria-label="`Remove instrument port mapping ${i+1}`" @click="configuration.portMappings?.splice(i,1)">Remove mapping</v-btn></div>
  <template v-if="!settingsOnly"><v-btn v-if="!configuration.software" variant="outlined" class="mt-4" @click="configuration.software={}">Record software requirements</v-btn><SoftwareEditor v-else :software="configuration.software" :components="selectedParts" /></template>
 </section>
</template>
