<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import type {Database,InventoryPC} from '../shared/types';
import BulkRecordEditor from './BulkRecordEditor.vue';
import type {BulkRequest} from '../shared/bulk-records';
import {locationPath,installationPCs} from '../shared/installations';
import {locationOperationRows,distributionVacancies,operationSearchText} from '../shared/location-operations';
const props=defineProps<{db:Database}>();
const emit=defineEmits<{editPc:[pc:InventoryPC];assign:[pc:InventoryPC];openLocation:[id:string];reload:[];notify:[message:string]}>();
const location=ref(''),status=ref(''),search=ref(''),attentionOnly=ref(false),repairOnly=ref(false),descendants=ref(true);
const selection=ref<string[]>([]),page=ref(1),bulkRequest=ref<BulkRequest|null>(null),bulkEditor=ref<{hasUnsavedChanges:()=>boolean;confirmDiscard:()=>boolean}|null>(null);
defineExpose({hasUnsavedChanges:()=>!!bulkEditor.value?.hasUnsavedChanges(),confirmDiscard:()=>bulkEditor.value?.confirmDiscard()??true});
function openBulk(action:'edit'|'delete'){bulkRequest.value=action==='delete'?{collection:'pcs',action,ids:[...selection.value]}:{collection:'pcs',action,ids:[...selection.value],patch:{}};}
watch([location,status,search,attentionOnly,repairOnly,descendants],()=>page.value=1);
watch(()=>props.db.pcs,pcs=>{const ids=new Set(pcs.map(p=>p.id));selection.value=selection.value.filter(id=>ids.has(id));});
const choices=computed(()=>[{title:'All locations',value:''},{title:'Unassigned PCs',value:'__unassigned'},...props.db.installationLocations.map(l=>({title:locationPath(l.id,props.db),value:l.id}))]);
const scopedPCs=computed(()=>location.value==='__unassigned'?props.db.pcs.filter(p=>!p.installationLocationId):location.value?installationPCs(location.value,props.db,descendants.value):props.db.pcs);
const rows=computed(()=>locationOperationRows(scopedPCs.value,props.db));
const visible=computed(()=>rows.value.filter(r=>(!status.value||(r.pc.lifecycle||'Planning')===status.value)&&(!attentionOnly.value||r.attention)&&(!repairOnly.value||r.faultyParts.length>0)&&operationSearchText(r.pc,props.db).includes(search.value.toLowerCase())));
const vacancies=computed(()=>location.value==='__unassigned'?[]:distributionVacancies(props.db,location.value,descendants.value));
const tableRows=computed(()=>visible.value.map(row=>({...row,id:row.pc.id,name:row.pc.name,physicalLocation:locationPath(row.pc.installationLocationId||'',props.db)||'Unassigned',equipment:row.context.labels.join(' / '),lifecycle:row.pc.lifecycle||'Planning'})));
const headers=[{title:'PC / serial',key:'name'},{title:'Physical location',key:'physicalLocation'},{title:'Equipment / build plan',key:'equipment'},{title:'Lifecycle',key:'lifecycle'},{title:'Installed parts',key:'installed'},{title:'Findings',key:'operationalStatus'},{title:'Actions',key:'actions',sortable:false}];
const hiddenSelected=computed(()=>selection.value.filter(id=>!visible.value.some(r=>r.pc.id===id)).length);
</script>
<template>
<section class="panel build-notes location-operations"><h2>Location operations</h2><p>Physical PC assignments and installed parts, with lifecycle and engineering findings for repair and distribution planning. Reservations are not installed parts.</p><div class="form-grid"><v-select v-model="location" label="Installation location" :items="choices" /><v-select v-model="status" label="Lifecycle status" :items="[{title:'All statuses',value:''},...['Planning','Building','Commissioned','In service','Maintenance','Parts only','Retired'].map(value=>({title:value,value}))]" /><v-text-field v-model="search" label="Search PCs, serials, equipment or locations" /><div><v-checkbox v-model="descendants" label="Include descendant locations" hide-details /><v-checkbox v-model="attentionOnly" label="Only PCs needing attention" hide-details /><v-checkbox v-model="repairOnly" label="Installed repair / quarantined parts" hide-details /></div></div><p role="status">{{visible.length}} PCs shown · {{visible.filter(r=>r.pc.lifecycle==='In service').length}} in service · {{visible.filter(r=>r.pc.lifecycle==='Maintenance').length}} in maintenance · {{visible.filter(r=>r.pc.lifecycle==='Parts only').length}} awaiting salvage · {{visible.filter(r=>!r.pc.installationLocationId).length}} unassigned shown</p>
<div class="bulk-toolbar"><v-btn variant="outlined" :disabled="!visible.length||new Set([...selection,...visible.map(r=>r.pc.id)]).size>500" @click="selection=[...new Set([...selection,...visible.map(r=>r.pc.id)])]">Add all {{visible.length}} matching PCs to selection</v-btn><v-btn variant="text" :disabled="!selection.length" @click="selection=[]">Clear selection</v-btn><v-btn color="primary" :disabled="!selection.length||selection.length>500" @click="openBulk('edit')">Edit selected PCs</v-btn><v-btn color="error" variant="outlined" :disabled="!selection.length||selection.length>500" @click="openBulk('delete')">Delete selected PCs</v-btn><p role="status">{{selection.length}} selected · {{hiddenSelected}} hidden by filters. Header checkbox selects the current page.</p></div>
<v-data-table v-model="selection" v-model:page="page" :headers="headers" :items="tableRows" item-value="id" show-select select-strategy="page" :items-per-page="25" :items-per-page-options="[10,25,50,100]" :mobile="false"><template #caption><caption class="sr-only">Actual PCs and repair status by installation location</caption></template><template #item.data-table-select="{item,props:checkbox}"><v-checkbox-btn v-bind="checkbox" :aria-label="`Select PC ${item.name}`" /></template><template #item.name="{item:row}"><strong>{{row.pc.name}}</strong><small>{{row.pc.serial||'No serial recorded'}}</small></template><template #item.physicalLocation="{item:row}">{{row.physicalLocation}}<small v-if="!row.pc.installationLocationId&&row.pc.location">Legacy location: {{row.pc.location}}</small></template><template #item.equipment="{item:row}">{{row.equipment||'No equipment or requirements link'}}<small>{{row.context.equipment.join(', ')}}</small><small>{{db.configurations.find(c=>c.id===row.pc.configurationId)?.name||'No build plan'}}</small></template><template #item.installed="{item:row}">{{row.installed}} installed<br>{{row.reserved}} reserved<br><strong v-if="row.faultyParts.length">{{row.faultyParts.reduce((n,p)=>n+p.allocation.quantity,0)}} repair / quarantined</strong></template><template #item.operationalStatus="{item:row}"><details><summary>{{row.operationalStatus}} · {{row.differences.length}} plan differences</summary><ul><li v-for="(finding,i) in row.pc.lifecycle==='Retired'?[]:row.report.findings.filter(f=>f.severity!=='pass')" :key="i">{{finding.title}}: {{finding.detail}}</li><li v-for="difference in row.differences" :key="difference">{{difference}}</li></ul><p v-for="part in row.faultyParts" :key="part.allocation.id">{{db.components.find(c=>c.id===part.stock.componentId)?.name}} · {{part.stock.serial||part.stock.assetTag||part.stock.id}} · {{part.stock.condition}} · repair: {{part.stock.repairReference||'Not recorded'}} · return: {{part.stock.supplierReturnReference||'Not recorded'}}</p><p>{{row.pc.notes}}</p></details></template><template #item.actions="{item:row}"><v-btn variant="text" @click="emit('editPc',row.pc)">Edit PC<span class="sr-only"> {{row.pc.name}}</span></v-btn><v-btn v-if="row.pc.lifecycle!=='Retired'" variant="text" @click="emit('assign',row.pc)">Assign / move<span class="sr-only"> {{row.pc.name}}</span></v-btn></template></v-data-table><p v-if="!visible.length">No PCs match these filters.</p></section>
<section class="panel build-notes"><h2>Locations needing distribution review</h2><p>Stations, benches and systems without an active assigned PC. This is an occupancy check; review target configurations and requirements before assigning a replacement. Parts-only units are excluded from active occupancy.</p><v-table><caption class="sr-only">Installation locations without active assigned PCs</caption><thead><tr><th scope="col">Location</th><th scope="col">Target configuration</th><th scope="col">Requirements</th><th scope="col">Action</th></tr></thead><tbody><tr v-for="item in vacancies" :key="item.id"><td>{{locationPath(item.id,db)}}</td><td>{{db.configurations.find(c=>c.id===item.targetConfigurationId)?.name||'Unspecified'}}</td><td>{{db.requirementsSets.find(s=>s.id===item.requirementSetId)?.name||'Not linked'}} · revision {{item.requirementRevision}}</td><td><v-btn variant="text" @click="emit('openLocation',item.id)">Open location<span class="sr-only"> {{item.name}}</span></v-btn></td></tr></tbody></v-table><p v-if="!vacancies.length">No vacant locations in this scope.</p></section>
<BulkRecordEditor ref="bulkEditor" :request="bulkRequest" :db="db" @close="bulkRequest=null" @reload="emit('reload')" @notify="message=>emit('notify',message)" @complete="selection=[]" />
</template>
