import { createApp } from 'vue';
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';
import 'vuetify/styles';
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg';
import App from './App.vue';
import './style.css';
import {loadAppearance,themePreference,systemDark} from './appearance';
await loadAppearance();
const dark=themePreference.value==='dark'||(themePreference.value==='system'&&systemDark.value);
document.documentElement.dataset.theme=dark?'dark':'light';
const vuetify=createVuetify({components,directives,icons:{defaultSet:'mdi',aliases,sets:{mdi}},theme:{defaultTheme:dark?'benchDark':'bench',themes:{bench:{dark:false,colors:{primary:'#284d37','on-primary':'#ffffff',secondary:'#435743','on-secondary':'#ffffff',background:'#f6f7f4','on-background':'#26322b',surface:'#ffffff','on-surface':'#26322b',error:'#922f28','on-error':'#ffffff',warning:'#735415','on-warning':'#ffffff',success:'#284d37','on-success':'#ffffff'}},benchDark:{dark:true,colors:{primary:'#a2dbb7','on-primary':'#10271a',secondary:'#bdd0c2','on-secondary':'#17231c',background:'#141c17','on-background':'#e3ede5',surface:'#202c24','on-surface':'#e3ede5',error:'#ffb4ad','on-error':'#41100b',warning:'#f3ce8d','on-warning':'#352409',success:'#a2dbb7','on-success':'#10271a'}}}},defaults:{VBtn:{rounded:'lg',elevation:0},VTextField:{variant:'outlined',density:'comfortable',hideDetails:'auto'},VSelect:{variant:'outlined',density:'comfortable',hideDetails:'auto'},VCombobox:{variant:'outlined',density:'comfortable',hideDetails:'auto'},VTextarea:{variant:'outlined',density:'comfortable',hideDetails:'auto'},VCard:{elevation:0,rounded:'lg'}}});
createApp(App).use(vuetify).mount('#app');
